### ISSUE TITLE
Project package no longer available in build environment

### ISSUE THREAD

**Issue by sethfischer** [readthedocs/readthedocs.org#10058]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sphinxcontrib-cadquery/
* Build URL: https://readthedocs.org/projects/sphinxcontrib-cadquery/builds/19562383/
* Read the Docs username: https://readthedocs.org/profiles/sethfischer/

This project uses Poetry to install dependencies with a `build.jobs.post_create_environment` user-defined job, in a manner [recommended by RTD](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry).

## Expected Result

As with [Build #19376393](https://readthedocs.org/projects/sphinxcontrib-cadquery/builds/19376393/), and previous builds, it is expected that the project package installed by `poetry install` is available when `python -m sphinx ...` is run.

## Actual Result

When `python -m sphinx ...` is run the project package can not be found. 

```
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-cadquery/envs/39/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-cadquery/checkouts/39/docs/conf.py", line 7, in <module>
    import sphinxcontrib.cadquery
ModuleNotFoundError: No module named 'sphinxcontrib.cadquery'
```

The last successful build was [Build #19376393](https://readthedocs.org/projects/sphinxcontrib-cadquery/builds/19376393/) dated Feb. 4, 2023. 1:54 a.m.

In both the expected and actual cases the `poetry install` command reports successful installation of the project package:

```
poetry install
⋮
Installing the current project: sphinxcontrib-cadquery (0.4.0)
```

**Comment by sethfischer** [comment]
Closing as I've replicated this error in my local environment.

**Comment by rlaphoenix** [comment]
I'm getting this error on multiple docs projects as well, not happening locally.

**Comment by sethfischer** [comment]
@rlaphoenix I was only able to replicated this error in my local environment once. As you are having the same issue it leads me to consider that something changed in the RTD environment.

My workaround was to revert back to using a `requirements.txt` committed to the repository.

During my investigation I came across two recommendations:

1. [Do not install Poetry into the project virtual environment](https://python-poetry.org/docs/#ci-recommendations). Instead Poetry should have a dedicated virtual environment separate to the project.
2. It is unusual to install some dependencies via pip before doing a poetry install.

The setup [recommended by RTD](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry) shares a virtual environment with Poetry, and some dependencies are installed via pip before doing a poetry install.

**Comment by rlaphoenix** [comment]
Take a look at my project VSGAN for its docs and rtd config for an example. Any import within `conf.py` that was installed via poetry fails as not found.

As mentioned somewhere else here, it looks as if `poetry` is installing somewhere different to the environment used during the `python -m sphinx` call. I cant get any successful build at all, and I've been trying all day.
