### ISSUE TITLE
Version mismatch OpenSSL & urllib

### ISSUE THREAD

**Issue by andersson1234** [readthedocs/readthedocs.org#10309]
## Details

* Read the Docs project URL: https://autopkgtest-cloud.readthedocs.io/en/latest/
* Build URL 1 (new failure): https://readthedocs.org/projects/autopkgtest-cloud/builds/20570264/
* Build URL 2 (before failures): https://readthedocs.org/projects/autopkgtest-cloud/builds/20168732/

## Expected Result

We have not changed anything in [this repo](https://git.launchpad.net/autopkgtest-cloud/) in the commits since the builds were succeeding that pertains to our readthedocs instance. Then today, I tried building again and we have an error in our builds like this:

```
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/autopkgtest-cloud/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autopkgtest-cloud/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/autopkgtest-cloud/envs/latest/lib/python3.7/site-packages/sphinx/builders/linkcheck.py", line 18, in <module>
    from requests import Response
  File "/home/docs/checkouts/readthedocs.org/user_builds/autopkgtest-cloud/envs/latest/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/docs/checkouts/readthedocs.org/user_builds/autopkgtest-cloud/envs/latest/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168
```

From this command:
```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
```

I'm wary to try and fix this from our side as I'm not 100% sure whether the issue is something in our repository or something external. I checked commits and nothing was changed in relation to RTD, and I tried to build an old version (from before these failures, that succeeded in the past) and it also failed.

**Comment by WhyNotHugo** [comment]
[Seeing this issue](https://readthedocs.org/projects/todoman/builds/20570994/) as well.

The latest `urlllib3` no longer supports older ssl versions. This includes the version installed in the build environment used by rtd.

There's not obvious fix for this, especially for tools that need to remain compatible with newer versions of urllib (e.g.:  you can't just pin an older version).

**Comment by benjaoming** [comment]
Thanks for reporting this :wave: 

That definitely seems like a new issue. Projects without a `.readthedocs.yaml` _or_ without `build.os` specified will run an old version of Read the Docs' build system with an old version of OpenSSL and are thus affected by this.

[urllib 2.0.2 was just released on May 4th](https://pypi.org/project/urllib3/2.0.2/), so you can either downgrade urllib in your requirements or specify `build.os` in your `.readthedocs.yaml`.

I'd highly recommend to use a configuration file and to specify the system which you are building on. By choosing `ubuntu-20.04` or `ubuntu-22.04`, things should work - I was just testing with `ubuntu-20.04` and I didn't receive complaints from urllib3 2.0.2: https://readthedocs.org/projects/test-builds/builds/20572471/.

To read more about `build.os`, see: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os

It's possible that the default build image will be upgraded with a newer version of OpenSSL. For that, I'd ask @humitos ? :blush:
