### ISSUE TITLE
Dependencies of PyPI package not getting installed only on RTD

### ISSUE THREAD

**Issue by grst** [readthedocs/readthedocs.org#10350]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/scirpy
* Build URL (if applicable): https://readthedocs.org/projects/scirpy/builds/20807592/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/grst/

## Expected Result

When a PyPI package gets installed via `pip install`, all its dependencies get installed as well. 

## Actual Result

Only the package gets installed, but not its dependencies. 

## Details

When building my project on RTD, sphinx autosummary failed because of some import error, which never occurred in local builds. I was able to pin it down to the [airr](https://pypi.org/project/airr/) package. 

To isolate the issue, I modified my `.readthedocs.yml` as follows to install and try to import the package even before the documentation gets built: 

```yml
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - python -m pip install --upgrade --no-cache-dir pip setuptools
      - python -m pip install --no-cache-dir airr
      - python -c "import airr"
```

The corresponding error log looks like this: 
```bash
> python -m pip install --no-cache-dir airr
Collecting airr
  Downloading airr-1.4.1.tar.gz (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.0/64.0 kB 27.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: airr
  Building wheel for airr (setup.py): started
  Building wheel for airr (setup.py): finished with status 'done'
  Created wheel for airr: filename=airr-1.4.1-py3-none-any.whl size=46333 sha256=ff7dde415b09aa5d61a8d7540f0f5797e4deff23b70a86e774ac8feacecd9ae2
  Stored in directory: /tmp/pip-ephem-wheel-cache-zekuayv_/wheels/25/5b/0a/caefc339d38f83a4edfd1c8cede3c0f892eefb0a61319aabaa
Successfully built airr
Installing collected packages: airr
Successfully installed airr-1.4.1 

> python -c "import airr"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/scirpy/envs/402/lib/python3.10/site-packages/airr/__init__.py", line 4, in <module>
    from airr.interface import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/scirpy/envs/402/lib/python3.10/site-packages/airr/interface.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

As you can see, the import fails because the `pandas` dependency didn't get installed. 

The trouble is, the `airr` package does seem to declare its dependencies properly, because if I run the following code locally, everything works as expected: 

```bash
> python -m virtualenv testenv
created virtual environment CPython3.10.9.final.0-64 in 127ms
  creator CPython3Posix(dest=/home/sturm/Downloads/testenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/sturm/.local/share/virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.7.2, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> source testenv/bin/activate
>  python -m pip install --no-cache-dir airr
Collecting airr
  Downloading airr-1.4.1.tar.gz (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.0/64.0 kB 983.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pandas>=0.24.0 (from airr)
  Downloading pandas-2.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 827.1 kB/s eta 0:00:00
Collecting pyyaml>=3.12 (from airr)
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 742.1 kB/s eta 0:00:00
Collecting yamlordereddictloader>=0.4.0 (from airr)
  Downloading yamlordereddictloader-0.4.0.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools>=2.0 in ./testenv/lib/python3.10/site-packages (from airr) (67.7.2)
Collecting python-dateutil>=2.8.2 (from pandas>=0.24.0->airr)
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 699.5 kB/s eta 0:00:00
Collecting pytz>=2020.1 (from pandas>=0.24.0->airr)
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 686.2 kB/s eta 0:00:00
Collecting tzdata>=2022.1 (from pandas>=0.24.0->airr)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 237.0 kB/s eta 0:00:00
Collecting numpy>=1.21.0 (from pandas>=0.24.0->airr)
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 835.8 kB/s eta 0:00:00
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas>=0.24.0->airr)
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: airr, yamlordereddictloader
  Building wheel for airr (setup.py) ... done
  Created wheel for airr: filename=airr-1.4.1-py3-none-any.whl size=46396 sha256=d2851e55f839ef734a6f25032e706c62560d2917899bde131b5952d1d8a27fb0
  Stored in directory: /home/sturm/tmp/pip-ephem-wheel-cache-17kf1x15/wheels/25/5b/0a/caefc339d38f83a4edfd1c8cede3c0f892eefb0a61319aabaa
  Building wheel for yamlordereddictloader (setup.py) ... done
  Created wheel for yamlordereddictloader: filename=yamlordereddictloader-0.4.0-py3-none-any.whl size=4053 sha256=c1be978736acad2c029b704cb62a96be7e749cc8941721cd9c87fce0e4937652
  Stored in directory: /home/sturm/tmp/pip-ephem-wheel-cache-17kf1x15/wheels/36/ab/cc/b583bb9d8c269b27a6b7bdc6e766588db00f79d8754774fe0d
Successfully built airr yamlordereddictloader
Installing collected packages: pytz, tzdata, six, pyyaml, numpy, yamlordereddictloader, python-dateutil, pandas, airr
Successfully installed airr-1.4.1 numpy-1.24.3 pandas-2.0.1 python-dateutil-2.8.2 pytz-2023.3 pyyaml-6.0 six-1.16.0 tzdata-2023.3 yamlordereddictloader-0.4.0

> python -c "import airr"
```

Any idea why the `pip install` behaves differently on RTD?

**Comment by humitos** [comment]
In the `setup.py` of that package they have this code for some reason:

```python
# Parse requirements
if os.environ.get('READTHEDOCS', None) == 'True':
    # Set empty install_requires to get install to work on readthedocs
    install_requires = []
else:
    with open('requirements.txt') as req:
        install_requires = req.read().splitlines()
```

So, it doesn't install any requirements on Read the Docs. I suppose you should contact the author about this decision.

**Comment by grst** [comment]
Thanks for noticing that, that is indeed a good explanation for my issue 😅
