### ISSUE TITLE
Issues in mkdocs build, can't import 'Sequence' from 'collections' issue

### ISSUE THREAD

**Issue by akanksha-singh-robomq** [readthedocs/readthedocs.org#10540]
## Hi,
I am using 3.11 python version for this...
I am using .readthedoc.yml file to build the documents on readthedocs site. Following https://blog.readthedocs.com/migrate-configuration-v2/ I have added these lines to my .readthedocs.yml file.
```
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
 
mkdocs:
  configuration: mkdocs.yml

## BUILD URL: 
https://readthedocs.org/projects/robomq/builds/21297080/

## ISSUE LOGS:
Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88,
 in _run_code File "/home/docs/checkouts/readthedocs.org/user_builds/robomq/envs/latest/lib/python3.11/site-
packages/mkdocs/__main__.py", line 12, in <module> from mkdocs import config File 
"/home/docs/checkouts/readthedocs.org/user_builds/robomq/envs/latest/lib/python3.11/site-
packages/mkdocs/config/__init__.py", line 2, in <module> from mkdocs.config.defaults import DEFAULT_SCHEMA File 
"/home/docs/checkouts/readthedocs.org/user_builds/robomq/envs/latest/lib/python3.11/site-
packages/mkdocs/config/defaults.py", line 4, in <module> from mkdocs.config import config_options File 
"/home/docs/checkouts/readthedocs.org/user_builds/robomq/envs/latest/lib/python3.11/site-
packages/mkdocs/config/config_options.py", line 3, in <module> from collections import Sequence ImportError: cannot 
import name 'Sequence' from 'collections' (/home/docs/.asdf/installs/python/3.11.4/lib/python3.11/collections/__init__.py)


PLEASE LET ME KNOW THE SOLUTION TO IT. 
Q1. Where to specify mkdocs version? Is this issue related to it?
Q2. Do we have create requirements.yml file to install the readthedocs theme?
Q3. My document are static page, what configuration I have to write in general so that it goes live?

```

**Comment by humitos** [comment]
Hi. Can you post the build URL where you are getting these errors?
