### ISSUE TITLE
Missing `sphinx_rtd_theme` required by default when appending `docs/conf.py`

### ISSUE THREAD

**Issue by cedk** [readthedocs/readthedocs.org#10626]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/trytond-product-price-list-cache/
* Build URL (if applicable): https://readthedocs.org/projects/trytond-product-price-list-cache/builds/21589803/

## Expected Result

As auto-created readthedocs.org specific configuration define 'sphinx_rtd_theme' as `html_theme`, it is expected that it install the required dependencies.
It was doing it until few days.

## Actual Result

The build fails because of:
```
Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
```

**Comment by witolddebski** [comment]
I added "sphinx_rtd_theme" in requirements.txt and it solved the issue. Please also mind that you need to add reference to requirements.txt in .readthedocs.yaml as follows (it is commented out by default):

```
python:
  install:
    - requirements: requirements.txt
```

**Comment by cedk** [comment]
Indeed but we should not have to maintain the dependencies of the default theme.conf.

**Comment by jayunit100** [comment]
seeing this as well...

**Comment by jayunit100** [comment]
```Running Sphinx v7.1.2
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 338, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 257, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 308, in init_templates
    self.theme = theme_factory.create(themename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/theming.py", line 228, in create
    raise ThemeError(__('no theme named %r found (missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_rtd_theme' found (missing theme.conf?)

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
```

**Comment by jayunit100** [comment]
ok, followed the above hint...  and it gets further but now i see

```

.. autosummary::
   :toctree: generated

   lumache
/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/checkouts/latest/docs/source/usage.rst:21: ERROR: Unknown directive type "autofunction".

.. autofunction:: lumache.get_random_ingredients
/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/checkouts/latest/docs/source/usage.rst:27: ERROR: Unknown directive type "autoexception".

.. autoexception:: lumache.InvalidKindError

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 328, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/storyworld0/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 438, in read
    raise SphinxError('root file %s not found' %
sphinx.errors.SphinxError: root file /home/docs/checkouts/readthedocs.org/user_builds/storyworld0/checkouts/latest/docs/index.rst not found

Sphinx error:
root file /home/docs/checkouts/readthedocs.org/user_builds/storyworld0/checkouts/latest/docs/index.rst not found

```

**Comment by stsewd** [comment]
Hi, for new projects we aren't installing the RTD nor other libs by default,  see https://blog.readthedocs.com/python-core-requirements-changed/. We recommend that your project installs the proper dependencies explicitly.

**Comment by cedk** [comment]
But the default conf.py is using sphinx_rtd_theme so it should be installed by default.
The minimal requirement provided on https://blog.readthedocs.com/migrate-configuration-v2/#adding-a-configuration-file does not set sphinx_rtd_theme as requirements.
As long as the appended configuration push sphinx_rtd_theme as dependency, it should be installed by default.

**Comment by humitos** [comment]
@cedk the default conf.py file is deprecated as well and it will be removed soon. See https://blog.readthedocs.com/doctool-without-configuration-file/

This issue is a temporal inconsistency, but I'll be removed once the date arrives 😊

**Comment by cedk** [comment]
I mean the part that is added automatically to the `conf.py`. In my case I have a `conf.py`.
What will then happen to my build?

**Comment by humitos** [comment]
@cedk 

> I mean the part that is added automatically to the `conf.py`. In my case I have a `conf.py`.

Hrm... that's a good point. I will re-open this issue for now.

> What will then happen to my build?

If you define the `html_theme` in your `conf.py` it should not be overwritten by Read the Docs.

**Comment by cedk** [comment]
> > What will then happen to my build?
> 
> If you define the `html_theme` in your `conf.py` it should not be overwritten by Read the Docs.

Agree but if I do not, what is the `html_theme` that will be used in the furture? If it is `sphinx_rtd_theme`, I think it should be installed automatically.

**Comment by humitos** [comment]
> what is the `html_theme` that will be used in the furture?

I opened a PR that removes this auto-configure the Read the Docs theme already at https://github.com/readthedocs/readthedocs.org/pull/10638. We need to coordinate how to deploy it now to avoid breaking existing projects.

**Comment by tkoskela** [comment]
The [tutorial template](https://github.com/readthedocs/tutorial-template) is failing the first build with this error for me
