### ISSUE TITLE
Builds failing with `html_theme` not set

### ISSUE THREAD

**Issue by st-bender** [readthedocs/readthedocs.org#10662]
Looks like  #10638 broke builds when `html_theme` is not set (see also comments in the PR).
I am not sure that breaking builds was intended.

```
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/conda/latest/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/checkouts/latest/docs/conf.py", line 164, in <module>
    'html_theme': html_theme,
NameError: name 'html_theme' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/conda/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/conda/latest/lib/python3.9/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/conda/latest/lib/python3.9/site-packages/sphinx/config.py", line 172, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/conda/latest/lib/python3.9/site-packages/sphinx/config.py", line 363, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/conda/latest/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/checkouts/latest/docs/conf.py", line 164, in <module>
    'html_theme': html_theme,
NameError: name 'html_theme' is not defined


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/conda/latest/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyeppaurora/checkouts/latest/docs/conf.py", line 164, in <module>
    'html_theme': html_theme,
NameError: name 'html_theme' is not defined
```

## Expected Result

The build should use RTD's default theme.

## Actual Result

Build error, see above.

**Comment by st-bender** [comment]
Thanks a lot!

**Comment by humitos** [comment]
We are releasing a fix for this today.
