### ISSUE TITLE
NameError: name 'html_theme' is not defined

### ISSUE THREAD

**Issue by cyberw** [readthedocs/readthedocs.org#10678]
## Details

* [Build URL](https://readthedocs.org/projects/locust/builds/21751777/)

## Expected Result

Should work, no changes since [this working build](https://readthedocs.org/projects/locust/builds/21675540/). Last time when I had issues I spent hours and hours trying to debug it before finding out it was an issue with the git checkout commands that seems to have affected everyone. So this time I'm just filing a bug right away, sorry if it is something on my end!

```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v4.3.2

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/envs/2386/lib/python3.11/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/checkouts/2386/docs/conf.py", line 233, in <module>
    'html_theme': html_theme,
                  ^^^^^^^^^^
NameError: name 'html_theme' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/envs/2386/lib/python3.11/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/envs/2386/lib/python3.11/site-packages/sphinx/application.py", line 216, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/envs/2386/lib/python3.11/site-packages/sphinx/config.py", line 173, in read
    namespace = eval_config_file(filename, tags)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/envs/2386/lib/python3.11/site-packages/sphinx/config.py", line 342, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/envs/2386/lib/python3.11/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/checkouts/2386/docs/conf.py", line 233, in <module>
    'html_theme': html_theme,
                  ^^^^^^^^^^
NameError: name 'html_theme' is not defined


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/envs/2386/lib/python3.11/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/locust/checkouts/2386/docs/conf.py", line 233, in <module>
    'html_theme': html_theme,
                  ^^^^^^^^^^
NameError: name 'html_theme' is not defined

Running `locust --help` command and storing output in /home/docs/checkouts/readthedocs.org/user_builds/locust/checkouts/2386/docs/cli-help-output.txt
Generating RST table for Locust environment variables and storing in /home/docs/checkouts/readthedocs.org/user_builds/locust/checkouts/2386/docs/config-options.rst
Command time: 1s Return: 2
```

**Comment by cyberw** [comment]
Duplicate of https://github.com/readthedocs/readthedocs.org/issues/10662
