### ISSUE TITLE
Search: display of search results is broken on PR builds

### ISSUE THREAD

**Issue by andreasabel** [readthedocs/readthedocs.org#10714]
First, big thanks! for providing this doc building & hosting service which we use for the Agda programming language.

I noticed that the display of search results does not fully work on PR builds of the documentation.  E.g. here I am searching for word "instance" in the build for PR agda/agda#6821:
https://agda--6821.org.readthedocs.build/en/6821/search.html?q=instance&check_keywords=yes&area=default
Using Google Chrome, this only displays the sections which contain the hits but not the hits themselves.
Turning on the JavaScript Console, I see errors thrown in `seachtools.js`:
> searchtools.js:97     GET https://agda--6821.org.readthedocs.build/en/6821/undefinedtools/command-line-options.html 
> searchtools.js:97     GET https://agda--6821.org.readthedocs.build/en/6821/undefinedlanguage/generalization-of-declared-variables.html 404
> searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
>    at Object.htmlToText (searchtools.js:167:53)
>    at Object.makeSearchSummary (searchtools.js:553:25)
>    at searchtools.js:102:20
<img width="840" alt="Screenshot 2023-09-06 at 04 36 46" src="https://github.com/readthedocs/readthedocs.org/assets/1155218/9ed1ab55-cca9-48cb-a4c5-a9f2e8b7879d">

It appears that the URLs are broken because some `undefined` sneaked in.  Consequently, the `htmlToText` gets `null` rather than the file content and crashes.

Following the exception into the code of `searchtools.js` I see code that builds the URL (`requestUrl`) by concatenation of some strings.
```js
  if (docBuilder === "dirhtml") {
    // dirhtml builder
    let dirname = docName + "/";
    if (dirname.match(/\/index\/$/))
      dirname = dirname.substring(0, dirname.length - 6);
    else if (dirname === "index/") dirname = "";
    requestUrl = contentRoot + dirname;
    linkUrl = requestUrl;
  } else {
    // normal html builders
    requestUrl = contentRoot + docName + docFileSuffix;
    linkUrl = docName + docLinkSuffix;
  }
```
Likely, one of these strings is `undefined` in PR-builds when it should be empty.
E.g. the valid link is https://agda--6821.org.readthedocs.build/en/6821/tools/command-line-options.html whereas GET tries https://agda--6821.org.readthedocs.build/en/6821/undefinedtools/command-line-options.html .

In the regular build everything works as expected, so the output of this query is what I expect also on the PR build:
https://agda.readthedocs.io/en/latest/search.html?q=instance&check_keywords=yes&area=default

**Comment by humitos** [comment]
Currently, we are not indexing files when building from pull requests due to the processing cost. However, we've talked about enabling this feature and it may happen in the future.

I think we have an exact issue for this, but I didn't find it / cc @stsewd

**Comment by stsewd** [comment]
Server side search is not enabled for PR builds, but the normal Sphinx search should work, so this is a bug.

**Comment by humitos** [comment]
We are moving away from the "auto injecting our search" concept (see https://github.com/readthedocs/addons/issues/72) and leaning more towards using our search via the addons. I don't think we will solve this issue and it can probably be closed as not planned.

**Comment by medmunds** [comment]
I am seeing this same behavior ("undefined" breaking search result links) in _non_-PR builds. It seems to depend on the specific query. Examples:
- https://anymail.dev/en/v10.2/search/?q=generate_message_id has broken results links (rendered client side)
- https://anymail.dev/en/v10.2/search/?q=message_id has working results links (apparently rendered server side)

At least in my case, the broken links are caused by (my docs/requirements.txt) trying to use Sphinx 7.2.x with sphinx-rtd-theme 1.3.x. There was a [breaking change in the Sphinx 7.2 searchtools.js](https://github.com/sphinx-doc/sphinx/issues/11608#issuecomment-1684410476) that requires `data-content_root` set on the `<html>` element. The necessary fix to sphinx-rtd-theme's layout.html template was added in https://github.com/readthedocs/sphinx_rtd_theme/pull/1507 and released in sphinx-rtd-theme 2.0.0rc2.

**Comment by humitos** [comment]
> At least in my case, the broken links are caused by (my docs/requirements.txt) trying to use Sphinx 7.2.x with sphinx-rtd-theme 1.3.x.

It seems you should upgrade the Read the Docs Sphinx theme to 2.x. Can you do that and let us know if this fixes the problem?

**Comment by medmunds** [comment]
Yes, upgrading to sphinx-rtd-theme 2.0 solved the broken search result links for my project:

* https://anymail.dev/en/v10.2/search/?q=generate_message_id [broken, sphinx-rtd-theme 1.3.x]
* https://anymail.dev/en/latest/search/?q=generate_message_id [fixed, sphinx-rtd-theme 2.0.x]
* https://anymail--360.org.readthedocs.build/en/360/search/?q=generate_message_id [recent PR build, also fixed]

At the time the original issue here was reported, sphinx-rtd-theme 2.0 hadn't yet been released. It's likely that release on 2023-11-27 solved the specific bug reported here, for anyone not pinning docs requirements. (So this should maybe be closed fixed rather than not planned.)

Additional info for anyone else still seeing broken Read the Docs search result links with "undefined" in the URLs, perhaps using other Sphinx themes or custom layouts:
* The problem isn't unique to PR builds; it's related to mismatched theme templates and Sphinx versions.
* The broken links only occur with searches where the browser console shows "Read the Docs search failed. Falling back to Sphinx search." (I guess this is always the case for PR builds, but the fallback to Sphinx search may also occur for *some* query strings on mainline builds, too.)
* The specific problem is that with Sphinx 7.2+, the base template for your search results (usually layout.html, usually found in your theme) must have `<html ... data-content_root="{{ content_root }}">`. If the `data-content_root` attribute is missing from the `<html>` tag, Sphinx's searchtools.js will construct broken search result urls containing "undefined". 
* Another symptom is that the snippets will be missing from the search results (for queries that fall back to Sphinx search).

**Comment by humitos** [comment]
I'm happy that `sphinx-rtd-theme 2.0` solved the issue. Also, thanks a lot for the detailed description here and how to detect the symptoms.
