### ISSUE TITLE
rtd compile failed with "ModuleNotFoundError: No module named 'sphinx_mdinclude'" ,why?

### ISSUE THREAD

**Issue by be-engineer** [readthedocs/readthedocs.org#10848]
## Details
https://readthedocs.org/projects/mikrotik-doc-cn/builds/22277027/

* Read the Docs project URL: https://readthedocs.org/projects/{your_project_slug}/
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

## Expected Result
 
I used to have been using sphinx_mdinclude, which can be compiled successfully, but it has failed today. For some reason?

*A description of what you wanted to happen*

## Actual Result

 raw error message as follows:
```
python -m sphinx -T -E -b html -d _build/doctrees -D language=zh . $READTHEDOCS_OUTPUT/html
Running Sphinx v7.2.6
loading translations [zh]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mikrotik-doc-cn/envs/latest/lib/python3.12/site-packages/sphinx/registry.py", line 447, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.12.0/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'sphinx_mdinclude'**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mikrotik-doc-cn/envs/latest/lib/python3.12/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/mikrotik-doc-cn/envs/latest/lib/python3.12/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mikrotik-doc-cn/envs/latest/lib/python3.12/site-packages/sphinx/application.py", line 406, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mikrotik-doc-cn/envs/latest/lib/python3.12/site-packages/sphinx/registry.py", line 450, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_mdinclude (exception: No module named 'sphinx_mdinclude')

Extension error:
Could not import extension sphinx_mdinclude (exception: No module named 'sphinx_mdinclude')
```
*A description of what actually happened*

**Comment by stsewd** [comment]
Hi, when you migrated to using the config file, you didn't port the installation of your project's requirements

https://github.com/be-engineer/MikroTik-doc-cn/blob/7b042a3a1186e3036fb579e2d2db884187e748f7/.readthedocs.yaml#L30-L35

**Comment by be-engineer** [comment]
> Hi, when you migrated to using the config file, you didn't port the installation of your project's requirements
> 
> https://github.com/be-engineer/MikroTik-doc-cn/blob/7b042a3a1186e3036fb579e2d2db884187e748f7/.readthedocs.yaml#L30-L35

ok,got it! Thanks!
