### ISSUE TITLE
whatever isntallation happened

### ISSUE THREAD

**Issue by gwilku** [readthedocs/readthedocs.org#10975]
https://readthedocs.org/projects/jscan-docs/builds/22975122/

I'm at loss here. why does all that work in an example RTD Sphinx build, but not in mine?
What jscan-docs module is the error about?
why are the errors such a nonsense?

**Comment by gwilku** [comment]
same happens in https://readthedocs.org/projects/jscan-docs/builds/22975189/
it cries about:       ValueError: No file/folder found for module jscan_docs
I am not asking pip to isntall jscan_docs - it's the name of my project, so where did it take that name from?


python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir .
Processing /home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/docs/checkouts/readthedocs.org/user_builds/jscan-docs/envs/latest/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-69zt7a0u/overlay/lib/python3.11/site-packages/flit_core/buildapi.py", line 31, in get_requires_for_build_wheel
          module = Module(info.module, Path.cwd())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-69zt7a0u/overlay/lib/python3.11/site-packages/flit_core/common.py", line 59, in __init__
          raise ValueError("No file/folder found for module {}".format(name))
      ValueError: No file/folder found for module jscan_docs
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
