### ISSUE TITLE
Error in Syslog Renderer

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#10990]
```
docs@web-extra-i-030bb0c0ac41975cd(com):~/checkouts/readthedocs.org$ django-admin migrate redirects 0006
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/docs/lib/python3.10/site-packages/structlog/stdlib.py", line 1087, in format
    ed = p(logger, meth_name, cast(EventDict, ed))
  File "/home/docs/checkouts/readthedocs.org/readthedocs/core/logs.py", line 115, in __call__
    + self._level_to_color.get(level, "")
AttributeError: 'SysLogRenderer' object has no attribute '_level_to_color'
```

Noticed this exception when running any console command on readthedocs.com. It didn't happen when running on readthedocs.org servers, which is odd since they're mostly identical.

**Comment by stsewd** [comment]
I'm seeing some errors related to logging on .org as well when running commands from the shell.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 971, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/docs/lib/python3.10/site-packages/structlog/stdlib.py", line 1087, in format
    ed = p(logger, meth_name, cast(EventDict, ed))
  File "/home/docs/checkouts/readthedocs.org/readthedocs/core/logs.py", line 115, in __call__
    + self._level_to_color.get(level, "")
AttributeError: 'SysLogRenderer' object has no attribute '_level_to_color'
```

**Comment by ericholscher** [comment]
Well that's good. I wasn't seeing them yesterday, but likely just need to remove that line in the logger :+1:

**Comment by ericholscher** [comment]
Pinning dep for now. Not sure where this core/logs logic came from, but not sure we need it anymore.
