### ISSUE TITLE
apidoc project path inconsistencies between local/home system and readthedocs

### ISSUE THREAD

**Issue by lzkelley** [readthedocs/readthedocs.org#11105]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/holodeck-gw/
* Build URL (if applicable): https://readthedocs.org/projects/holodeck-gw/builds/23399810/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/lzkelley/

## Error

The build works fine when I run it locally using `make html`, but fails on readthedocs.  I'm running apidoc from my `conf.py` file using:

```
def run_apidoc(_):
    from sphinx.ext.apidoc import main
    argv = [
        *apidoc_command_options,
        '-o', apidoc_module_dir,
        '../PROJECT',    # <---- line of interest.
        *apidoc_excluded_paths,
    ]
    main(argv)
```

At some point I was able to change the indicated path to get the project to build successfully on readthedocs, but then it would fail on my local system.  I also cannot reproduce that at the moment, however.

The error I'm getting is:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/holodeck-gw/envs/docs/lib/python3.9/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/holodeck-gw/envs/docs/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/holodeck-gw/envs/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/holodeck-gw/envs/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/holodeck-gw/envs/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 423, in read
    raise SphinxError('root file %s not found' %
sphinx.errors.SphinxError: root file /home/docs/checkouts/readthedocs.org/user_builds/holodeck-gw/checkouts/docs/docs/index.rst not found

Sphinx error:
root file /home/docs/checkouts/readthedocs.org/user_builds/holodeck-gw/checkouts/docs/docs/index.rst not found
```

### Structure

```
PACKAGE
    docs/
        source/
            index.rst
            ...
        conf.py
        Makefile
        requirements.txt
        ...
    PROJECT
        __init__.py
        ...
    .readthedocs.yml
    setup.py
    requirements.txt
    ...
```
    
### sphinx files

readthedocs.yml:
```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - python setup.py build_ext -i
      - python setup.py develop

sphinx:
   configuration: docs/conf.py

formats:
   - pdf

python:
   install:
   - requirements: docs/requirements.txt
   - requirements: requirements.txt
```
The extra `post_install` is to build cython modules imported by the project.

conf.py

```
project = 'PROJECT'
copyright = '2024, AUTHOR'
author = 'AUTHOR'
release = 'VERSION'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.duration',
    'sphinx.ext.mathjax',
    'sphinx.ext.autosectionlabel',
]

templates_path = []
exclude_patterns = []

mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'

html_theme = 'sphinx_rtd_theme'
html_static_path = []

apidoc_module_dir = 'source/apidoc_modules'
apidoc_excluded_paths = ['../PROJECT/file1.py', '../PROJECT/file2.py']
apidoc_command_options = [
    '-M',  # put modules before submodules
    '-e',  # Create separate files for each module
    '-P',  # Include private modules
    '-T',  # Include docstrings in the table of contents
    '-f',   # Overwrite existing files
]

def run_apidoc(_):
    from sphinx.ext.apidoc import main
    argv = [
        *apidoc_command_options,
        '-o', apidoc_module_dir,
        '../PROJECT',
        *apidoc_excluded_paths,
    ]
    main(argv)

def setup(app):
    app.connect('builder-inited', run_apidoc)
```

Makefile:

```
SPHINXOPTS    ?= -c . -w sphinx.log -j 8   # -vvv
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build
APIDOCDIR     = $(SOURCEDIR)/apidoc_modules

help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

clean:
	rm $(APIDOCDIR)/*
	@$(SPHINXBUILD) -M clean "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

**Comment by lzkelley** [comment]
I've disabled the apidoc components and still have the error, so I think it's actually more generic and not specifically related to apidoc.

**Comment by lzkelley** [comment]
This issue is the same as https://github.com/readthedocs/readthedocs.org/issues/7883

readthedocs REQUIRES the conf.py file to be in the source directory (the directory containing the top-level `index.rst` file) despite this not being (clearly?) stated anywhere.
