### ISSUE TITLE
Build fails with `BadZipFile`

### ISSUE THREAD

**Issue by tsmethurst** [readthedocs/readthedocs.org#11247]
## Details

* Read the Docs project URL: https://beta.readthedocs.org/projects/gotosocial/
* Build URL (if applicable): https://beta.readthedocs.org/projects/gotosocial/builds/23901004/

## Expected Result

The build should pass.

## Actual Result

An error is returned with the following stacktrace:

```
python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/mkdocs/__main__.py", line 361, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/mkdocs/commands/build.py", line 277, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/mkdocs/plugins.py", line 527, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/material/plugins/social/plugin.py", line 141, in on_config
    self.font = self._load_font(config)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/material/plugins/social/plugin.py", line 457, in _load_font
    self._load_font_from_google(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/site-packages/material/plugins/social/plugin.py", line 480, in _load_font_from_google
    zip = ZipFile(tmp)
          ^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/zipfile/__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gotosocial/conda/2789/lib/python3.12/zipfile/__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

This error has been occurring for the last 4 hours or so, but we didn't change anything to make this occur. I tried fixing it by updating dependencies in this pull request: https://github.com/superseriousbusiness/gotosocial/pull/2789

It seems to have helped when doing local builds, but builds on the readthedocs system still fail.

**Comment by tsmethurst** [comment]
Related issue: https://github.com/readthedocs/readthedocs.org/issues/2420

**Comment by stsewd** [comment]
Hi, this is likely a problem with an unpinned dependency (direct or transit) from your project. Seems like you were able to replicate this locally, make sure you are using the same dependencies on RTD as locally (try running the exact commands in a clean environment).

**Comment by tsmethurst** [comment]
Hiya, thanks for the response. One weird thing I've noticed is that the output of `cat docs/environment.yml` shown in the build console [here](https://readthedocs.org/projects/gotosocial/builds/23901462/) is not actually equal to the code that's currently on git [here](https://github.com/superseriousbusiness/gotosocial/pull/2789/files#diff-04dc0c15947f2a47931f3d9e7ccf5af610059cef1b86e24ea32effa2dff58eb6) -- in the former, `mkdocs` is present in the pip dependencies, but in the latter, it's present (as it's always been) as a conda dependency. Could this be what's causing the issue? It's absolutely baffling that the result of `cat` is different from what's actually there :thinking:

**Comment by tsmethurst** [comment]
Hmm okay I examined the log files in a bit more detail and it's failing on trying to load a font from google. Perhaps it's a google CDN issue then? And the reason it works on my machine and not the RtD CI/CD machine is because they're in different regions? I will try running the build again later and see if it's fixed...

**Comment by tsmethurst** [comment]
Update on this, it's definitely to do with the Roboto fonts not being able to be downloaded from the Google fonts API. After vendoring the fonts in [this pull request](https://github.com/superseriousbusiness/gotosocial/pull/2789), the build now works, because mkdocs uses the vendored/cached fonts and skips the step of trying to download them from google.

I'll close the issue, since it's almost certainly just an issue with Google, not an issue with RtD.
