### ISSUE TITLE
The 'furo' theme inherits from 'basic-ng', which is not a loaded theme.

### ISSUE THREAD

**Issue by ShaneHarvey** [readthedocs/readthedocs.org#11282]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pymongo
* Build URL (if applicable): https://readthedocs.org/projects/pymongo/builds/24088961/

## Expected Result

A successful build.

## Actual Result
```
python -m sphinx -T -W --keep-going -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v7.3.0
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymongo/envs/1599/lib/python3.11/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymongo/envs/1599/lib/python3.11/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymongo/envs/1599/lib/python3.11/site-packages/sphinx/application.py", line 338, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymongo/envs/1599/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 228, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymongo/envs/1599/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 278, in init_templates
    self.theme = theme_factory.create(theme_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymongo/envs/1599/lib/python3.11/site-packages/sphinx/theming.py", line 228, in create
    themes, theme_dirs, tmp_dirs = _load_theme_with_ancestors(self._themes, name)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymongo/envs/1599/lib/python3.11/site-packages/sphinx/theming.py", line 266, in _load_theme_with_ancestors
    raise ThemeError(msg)
sphinx.errors.ThemeError: The 'furo' theme inherits from 'basic-ng', which is not a loaded theme. Loaded themes are: agogo, alabaster, basic, bizstyle, classic, default, epub, furo, haiku, nature, nonav, pyramid, scrolls, sphinxdoc, traditional

Theme error:
The 'furo' theme inherits from 'basic-ng', which is not a loaded theme. Loaded themes are: agogo, alabaster, basic, bizstyle, classic, default, epub, furo, haiku, nature, nonav, pyramid, scrolls, sphinxdoc, traditional
```

Is this a bug? We've been using the furo theme for a year now and haven't encountered this error before.

**Comment by agjohnson** [comment]
Yeah, this doesn't look to be directly related to the tomli issue. I didn't look into the changes in 7.3 yet, but it seems both are somewhere around HTMLThemeFactory at least

**Comment by AA-Turner** [comment]
[Sphinx 7.3.2](https://pypi.org/project/Sphinx/7.3.2/) has been released with fixes.

A

**Comment by ShaneHarvey** [comment]
Thanks all!
