### ISSUE TITLE
Build fails with TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Davide-sd** [readthedocs/readthedocs.org#11306]
## Details

* Read the Docs project URL: [https://readthedocs.org/projects/sympy-plot-backends/](https://readthedocs.org/projects/sympy-plot-backends/)
* Build URL (if applicable): [https://readthedocs.org/projects/sympy-plot-backends/builds/24204752/](https://readthedocs.org/projects/sympy-plot-backends/builds/24204752/)
* Read the Docs username (if applicable): [https://readthedocs.org/profiles/Davide_sd/](https://readthedocs.org/profiles/Davide_sd/)

## Expected Result

Successfully building the documentation.

## Actual Result

I'm getting this error, from which I'm unable to pinpoint what the problem is.

```text
# python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

 Running Sphinx v7.3.7

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 338, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 220, in init
    self.build_info = self.create_build_info()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 246, in create_build_info
    return BuildInfo(self.config, self.tags, frozenset({'html'}))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 142, in __init__
    values = {c.name: c.value for c in config.filter(config_categories)}
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 142, in <dictcomp>
    values = {c.name: c.value for c in config.filter(config_categories)}
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 451, in <genexpr>
    return (value for value in self if value.rebuild in rebuild)
TypeError: unhashable type: 'list'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/sympy-plot-backends/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 451, in <genexpr>
    return (value for value in self if value.rebuild in rebuild)
TypeError: unhashable type: 'list'
The full traceback has been saved in /tmp/sphinx-err-9pvnt8ll.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Note that my last successful build was about 2 weeks ago, using Sphinx v7.2.6. Since then, I haven't modified `.readthedocs.yml`, but I changed `conf.py` (on my local machine, the build runs fine with an older version of Sphinx).

The error message mentions the file `/tmp/sphinx-err-9pvnt8ll.log`. Is there a way to access it?

**Comment by humitos** [comment]
Hi. The latest successful build I found in your documentation was using Sphinx v7.2.6. I assume the upgrade to 7.3.7 may break something on your project. I'd suggest you to pin the version of Sphinx to 7.2.6 as a first test to verify if this is related to the Sphinx version or not.

**Comment by Davide-sd** [comment]
Hi @humitos , thanks for the suggestion. I've set `sphinx==7.2.6` in `requirements.txt` and the build succeeded. Then, I guess it's something related to Sphinx...
