### ISSUE TITLE
Unable to get requirements to build Wheel

### ISSUE THREAD

**Issue by Skrillx13** [readthedocs/readthedocs.org#11591]
## Details

-  **Read the Docs Project URL**: https://app.readthedocs.org/projects/lumaches/
-  **Build URL**: https://app.readthedocs.org/projects/lumaches/builds/25557035/
-  **Read the Docs Username**: https://app.readthedocs.org/profiles/Skrillx/

Basically, I have a Python Libary Project that I am working on, and I have a docs/ directory inside of it. I've added all the neecssary configurations and files for RTD to work, but it's still not working. Theres a GitHub repo containing the files I have, and I installed a few extra packages, mainly these:

`% pip install wheel`
`% pip install setuptools`
`% pip install twine`

## Expected Result

I have configured all the things required to build my documentation with ReadTheDocs, and expected the build to work.

## Actual Result

When I try to build the documentation, it stops at this process, `python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir . `, and gives the following error codes:

Processing /home/docs/checkouts/readthedocs.org/user_builds/lumaches/checkouts/latest
--
2 | Installing build dependencies: started
3 | Installing build dependencies: finished with status 'done'
4 | Getting requirements to build wheel: started
5 | Getting requirements to build wheel: finished with status 'error'
6 | error: subprocess-exited-with-error
7 |  
8 | × Getting requirements to build wheel did not run successfully.
9 | │ exit code: 1
10 | ╰─> [12 lines of output]
11 | Traceback (most recent call last):
12 | File "/home/docs/checkouts/readthedocs.org/user_builds/lumaches/envs/latest/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
13 | main()
14 | File "/home/docs/checkouts/readthedocs.org/user_builds/lumaches/envs/latest/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
15 | json_out['return_val'] = hook(**hook_input['kwargs'])
16 | File "/home/docs/checkouts/readthedocs.org/user_builds/lumaches/envs/latest/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
17 | return hook(config_settings)
18 | File "/tmp/pip-build-env-4lay2od6/overlay/lib/python3.10/site-packages/flit_core/buildapi.py", line 31, in get_requires_for_build_wheel
19 | module = Module(info.module, Path.cwd())
20 | File "/tmp/pip-build-env-4lay2od6/overlay/lib/python3.10/site-packages/flit_core/common.py", line 59, in __init__
21 | raise ValueError("No file/folder found for module {}".format(name))
22 | ValueError: No file/folder found for module Lumache
23 | [end of output]
24 |  
25 | note: This error originates from a subprocess, and is likely not a problem with pip.
26 | error: subprocess-exited-with-error
27 |  
28 | × Getting requirements to build wheel did not run successfully.
29 | │ exit code: 1
30 | ╰─> See above for output.
31 |  
32 | note: This error originates from a subprocess, and is likely not a problem with pip.

Processing /home/docs/checkouts/readthedocs.org/user_builds/lumaches/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1[2](https://app.readthedocs.org/projects/lumaches/builds/25557035/#243197660--2) lines of output]
      Traceback (most recent call last):
        File "/home/docs/checkouts/readthedocs.org/user_builds/lumaches/envs/latest/lib/python[3](https://app.readthedocs.org/projects/lumaches/builds/25557035/#243197660--3).10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/docs/checkouts/readthedocs.org/user_builds/lumaches/envs/latest/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/docs/checkouts/readthedocs.org/user_builds/lumaches/envs/latest/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-[4](https://app.readthedocs.org/projects/lumaches/builds/25557035/#243197660--4)lay2od6/overlay/lib/python3.10/site-packages/flit_core/buildapi.py", line 31, in get_requires_for_build_wheel
          module = Module(info.module, Path.cwd())
        File "/tmp/pip-build-env-4lay2od6/overlay/lib/python3.10/site-packages/flit_core/common.py", line [5](https://app.readthedocs.org/projects/lumaches/builds/25557035/#243197660--5)9, in __init__
          raise ValueError("No file/folder found for module {}".format(name))
      ValueError: No file/folder found for module Lumache
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by humitos** [comment]
> ValueError: No file/folder found for module Lumache

This seems to be an issue with the library you are trying to install. Maybe the package is corrupted? Maybe it's using a relative path that works in your computer but it doesn't when ran from a different directory?

It does not seem to be an issue with Read the Docs.

**Comment by Skrillx13** [comment]
> > ValueError: No file/folder found for module Lumache
> 
> This seems to be an issue with the library you are trying to install. Maybe the package is corrupted? Maybe it's using a relative path that works in your computer but it doesn't when ran from a different directory?
> 
> It does not seem to be an issue with Read the Docs.

alright if it's a libary issue ill sort that out but thanks for the clarification
