### ISSUE TITLE
Celery broken in RTD 2.3.12 

### ISSUE THREAD

**Issue by boerngen-schmidt** [readthedocs/readthedocs.org#4125]
## Details

Own on premise Docker container fails to start celery with current requirements

## Expected Result

Starting celery with `celery worker -A readthedocs -Q default,celery,web,builder -l DEBUG -c 2`

## Actual Result

```bash
(venv) rtd@rtd:~/readthedocs.org$ celery worker -A readthedocs -Q default,celery,web,builder -l DEBUG -c 2
Traceback (most recent call last):
  File "/home/rtd/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/home/rtd/venv/lib/python2.7/site-packages/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async
```

## Fix
Either fix kombu to Version `(venv) rtd@rtd:~/readthedocs.org$ pip install kombu==4.1.0` which works with celery 4.1.0
** OR **
Upgrade celery and use newest version of kombu `(venv) rtd@rtd:~/readthedocs.org$ pip install celery==4.1.1`

**Comment by humitos** [comment]
We are not experimenting this issue in production or in our local environments.

Anyway, I just created a PR that updates Celery together with other packages as well: #4124.
