### ISSUE TITLE
Upgrade celery to >= 4.2

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4643]
We may need to do some changes before upgrading celery to 4.2, as we face some issues (https://github.com/rtfd/readthedocs.org/issues/4640).

Some options are:

- Require to run celery (`always_eager=False`) in dev
- Maybe this is a bug on celery?
   - Or maybe we can send a patch to allow to pass the `disable_sync_subtask` option as mention in https://github.com/rtfd/readthedocs.org/issues/4640#issuecomment-422232637

**Comment by humitos** [comment]
I just tried with `celery==4.2.1` and I got this error:

```
[20/Jan/2019 12:41:29] readthedocs.doc_builder.environments:553[28603]: ERROR (Build) [test-builds:latest] Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
Traceback (most recent call last):
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 562, in run_build
    epub=bool(outcomes['epub']),
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 731, in update_app_instances
    commit=self.build['commit'],
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/core/utils/__init__.py", line 52, in broadcast
    task_promise = chord(tasks, callback).apply_async()
  File "/home/humitos/.pyenv/versions/3.6.6/envs/readthedocs.org/lib/python3.6/site-packages/celery/canvas.py", line 1230, in apply_async
    body=body, task_id=task_id, **options)
  File "/home/humitos/.pyenv/versions/3.6.6/envs/readthedocs.org/lib/python3.6/site-packages/celery/canvas.py", line 1239, in apply
    args=(tasks.apply(args, kwargs).get(propagate=propagate),),
  File "/home/humitos/.pyenv/versions/3.6.6/envs/readthedocs.org/lib/python3.6/site-packages/celery/result.py", line 671, in get
    on_interval=on_interval,
  File "/home/humitos/.pyenv/versions/3.6.6/envs/readthedocs.org/lib/python3.6/site-packages/celery/result.py", line 722, in join
    assert_will_not_block()
  File "/home/humitos/.pyenv/versions/3.6.6/envs/readthedocs.org/lib/python3.6/site-packages/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks

[20/Jan/2019 12:41:29] readthedocs.doc_builder.environments:653[28603]: ERROR Build failed with unhandled exception: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

**Comment by stsewd** [comment]
This happens when we execute the task with a callback

https://github.com/rtfd/readthedocs.org/blob/54397a07a1baed5b183c0535093643467c3edaba/readthedocs/core/utils/__init__.py#L50

The task is already running in a celery task, so when we call `chord`, it's basically doing something like

```
r = task.delay(...)get()
callback(r).delay()
```

That get is causing the error :)

I'll try to see how we can fix/refactor this

**Comment by stsewd** [comment]
So, we can't execute the callback from outside a task anyway, it will block the request :/. So, I guess we just need to ignore the error as the docs shown.

**Comment by stsewd** [comment]
I tried a lot of ways, but looks like there is a bug in celery :/

```python
    # Celery's Group class does some special handling when an iterable with
    # len() == 1 is passed in. This will be hit if there is only one server
    # defined in the above queue lists
    if len(tasks) > 1:
        task_promise = group(*tasks).apply_async()
    else:
        task_promise = group(tasks).apply_async()
    if callback:
        task_promise.get(disable_sync_subtasks=False)
        return callback.apply_async()
    return task_promise

```


https://github.com/celery/celery/issues/5330
