### ISSUE TITLE
No such file or directory: '$HOME': '$HOME'

### ISSUE THREAD

**Issue by TiDjY35** [readthedocs/readthedocs.org#5880]
## Details

* Read the Docs project URL: 
not compiled

* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

when compile my project i've an error

python3.7 -mvirtualenv --no-site-packages --no-download /root/readthedocs.org/user_builds/th3/envs/latest
Traceback (most recent call last):
  File "/root/readthedocs.org/readthedocs/doc_builder/environments.py", line 183, in run
    env=environment,
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '$HOME': '$HOME'

the directory /root/readthedocs.org/user_builds/th3/envs/latest doesn't exist

## Actual Result

[04/Jul/2019 15:50:28] readthedocs.vcs_support.utils:129[24164]: DEBUG Lock (th3): Releasing
[04/Jul/2019 15:50:28] readthedocs.doc_builder.environments:618[24164]: WARNING (Build) [th3:latest] Command python3.7 -mvirtualenv --no-site-packages --no-download /root/readthedocs.org/user_builds/th3/envs/latest failed:
Traceback (most recent call last):
  File "/root/readthedocs.org/readthedocs/doc_builder/environments.py", line 183, in run
    env=environment,
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '$HOME': '$HOME'
Traceback (most recent call last):
  File "/root/readthedocs.org/readthedocs/projects/tasks.py", line 539, in run_build
    self.setup_python_environment()
  File "/root/readthedocs.org/readthedocs/projects/tasks.py", line 892, in setup_python_environment
    self.python_env.setup_base()
  File "/root/readthedocs.org/readthedocs/doc_builder/python_environments.py", line 277, in setup_base
    cwd='$HOME',
  File "/root/readthedocs.org/readthedocs/doc_builder/environments.py", line 631, in run
    return super().run(*cmd, **kwargs)
  File "/root/readthedocs.org/readthedocs/doc_builder/environments.py", line 418, in run
    return self.run_command_class(cls=self.command_class, cmd=cmd, **kwargs)
  File "/root/readthedocs.org/readthedocs/doc_builder/environments.py", line 637, in run_command_class
    return super().run_command_class(*cmd, **kwargs)
  File "/root/readthedocs.org/readthedocs/doc_builder/environments.py", line 489, in run_command_class
    raise BuildEnvironmentWarning(msg)
readthedocs.doc_builder.exceptions.BuildEnvironmentWarning: Command python3.7 -mvirtualenv --no-site-packages --no-download /root/readthedocs.org/user_builds/th3/envs/latest failed:
Traceback (most recent call last):
  File "/root/readthedocs.org/readthedocs/doc_builder/environments.py", line 183, in run
    env=environment,
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '$HOME': '$HOME'

**Comment by stsewd** [comment]
Please provide the build url and project page.

**Comment by humitos** [comment]
@TiDjY35 can you explain a little more your problem? It seems that the "Expected result" is an error as well.

**Comment by JediKev** [comment]
If anyone runs into this error _and you're using UWSGI_, go to your UWSGI file and change:
```
virtualenv=/location
```
TO
```
home=/location
```

Restart UWSGI and NGINX (or Apache) and it should work without a hitch.

Cheers.
