### ISSUE TITLE
Dockerized readthedocs.org Install Fails At migrate.py with SyntaxError

### ISSUE THREAD

**Issue by kb1lqc** [readthedocs/readthedocs.org#5902]
## Details

Following both the Local VM install and the developer install I can't get a dockerized readthedocs.org to install correctly. More specifically I keep getting an error when I run the manage.py step. 

https://docs.readthedocs.io/en/stable/development/install.html

Note, I have been forced to modify the steps to use python3 and specifically python3.5 as the documentation as written will A) automatically use python 2.7 and B) have other build errors with the latest Python 3.

* Read the Docs project URL: None
* Build URL (if applicable): None
* Read the Docs username (if applicable): None

## Expected Result
proper install and database migration.
*A description of what you wanted to happen*

## Actual Result
```
Step 19/19 : RUN python3 ./manage.py migrate
 ---> Running in 92945514d013
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/checkouts/readthedocs.org/readthedocs/projects/models.py", line 41, in <module>
    from readthedocs.vcs_support.backends import backend_cls
  File "/checkouts/readthedocs.org/readthedocs/vcs_support/backends/__init__.py", line 5, in <module>
    from . import bzr, hg, git, svn
  File "/checkouts/readthedocs.org/readthedocs/vcs_support/backends/git.py", line 13, in <module>
    from readthedocs.config import ALL
  File "/checkouts/readthedocs.org/readthedocs/config/__init__.py", line 4, in <module>
    from .config import *  # noqa
  File "/checkouts/readthedocs.org/readthedocs/config/config.py", line 86
    f"Configuration file not found in: {directory}",
                                                  ^
SyntaxError: invalid syntax
The command '/bin/sh -c python3 ./manage.py migrate' returned a non-zero code: 1
```
*A description of what actually happened*

Using the following Dockerfile I can't get past the manage.py step (there seems to be no official Dockerfile and the explicit instructions followed exactly simply don't work either).

```
FROM debian

# Update the package repository
RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y wget dpkg python3.5


# Install locales package and configure, suppress questions
RUN apt-get install -y python3-setuptools build-essential python3-dev python3-pip
RUN apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev
RUN apt-get install -y git
RUN apt-get install -y redis-server

RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-amd64.deb
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-amd64.deb.sha512
RUN shasum -a 512 -c elasticsearch-7.2.0-amd64.deb.sha512 
RUN dpkg -i elasticsearch-7.2.0-amd64.deb
RUN pip3 install sphinx
RUN apt-get install -y python3-venv

RUN mkdir checkouts
WORKDIR checkouts
RUN git clone https://github.com/rtfd/readthedocs.org.git
WORKDIR readthedocs.org
RUN pip3 install -r requirements.txt

RUN python3 ./manage.py migrate
```

**Comment by stsewd** [comment]
Read the Docs only works with python 3.6 (that's on the docs). We use `f`strings in our code, those are only supported in +3.6.

**Comment by kb1lqc** [comment]
@stsewd What's the proper procedure for installation then? The docs I linked to still use Python 2 commands.

**Comment by stsewd** [comment]
> The docs I linked to still use Python 2 commands.

I didn't find any mention of python2, in the virtualenv creation you can see that python3 is used.

> What's the proper procedure for installation then?

Use python3.6 as it's mentioned in the guide
