### ISSUE TITLE
Recent builds fail because of an error that was fixed a while ago

### ISSUE THREAD

**Issue by johannfaouzi** [readthedocs/readthedocs.org#6061]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyts/
* Build URL (if applicable):
* Read the Docs username (if applicable): johannfaouzi

There is something a bit weird that is happening with the builds of my project: sometimes the build fails because of an error that was fixed a while ago, and I don't understand why this is occuring.

In my [api.rst](https://github.com/johannfaouzi/pyts/blob/master/doc/api.rst#modpytsdatasets-dataset-loading-utilities) file, I used the wrong template for the `datasets` module: I used the `class.rst` instead of `function.rst`. I fixed this several commits ago, but some recent builds fail because of this (see this [build](https://readthedocs.org/projects/pyts/builds/9493476/) or that [build](https://readthedocs.org/projects/pyts/builds/9493412/) for instance). I did not change anything in the corresponding file.

Having a build failed because of this is a bit confusing.

## Expected Result

Build succeeded.

## Actual Result

```python
reading sources... [ 51%] generated/pyts.datasets.fetch_ucr_dataset
WARNING: error while formatting arguments for pyts.datasets.fetch_ucr_dataset: 'function' object has no attribute '__mro__'
WARNING: [numpydoc] While processing docstring for 'pyts.datasets.fetch_ucr_dataset'

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 71, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2346, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2376, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2649, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 131, in run
    documenter.generate(more_content=self.content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1247, in generate
    all_members=all_members)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 816, in generate
    self.add_content(more_content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1229, in add_content
    ModuleLevelDocumenter.add_content(self, more_content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 554, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 514, in process_doc
    self.options, docstringlines)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/numpydoc/numpydoc.py", line 177, in mangle_docstrings
    builder=app.builder)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/numpydoc/docscrape_sphinx.py", line 456, in get_doc_object
    config=config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/numpydoc/docscrape_sphinx.py", line 424, in __init__
    ClassDoc.__init__(self, obj, doc=doc, func_doc=None, config=config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyts/envs/latest/lib/python3.7/site-packages/numpydoc/docscrape.py", line 626, in __init__
    raise ValueError("Expected a class or None, but got %r" % cls)
ValueError: Expected a class or None, but got <function fetch_ucr_dataset at 0x7fcea6849ea0>

```

**Comment by humitos** [comment]
Try wiping the version. It may be and old cache file interfering. Please, report back if it continues happening.
