### ISSUE TITLE
Unable To Update Build

### ISSUE THREAD

**Issue by JediKev** [readthedocs/readthedocs.org#6098]
## Details

Hello everyone. I have a local installation of RTD that has been running for over a year now without any issues. I recently added an SSL certificate for the main domain and somehow this broke the `update_build` function. I can see the payload being sent from GitHub, I can see the payload being delivered to RTD with `200 Success`, and I can see the build in Triggered state but nothing happens after this. It gets stuck at "Triggered". I read up on previous related Issues and have tried all the suggestions (creating `local_settings.py` file, checking all my `SLUMBER_*` vars, etc.) to no avail.

## Expected Result

The expected result would be for the Build to exit Triggered state and finish building the documentation successfully.

## Actual Result

The actual result is stuck in Triggered state. I will post the Debug logs below for a single update attempt:
```
[23/Aug/2019 08:41:46] readthedocs.core.views.hooks:83[1417]: INFO (Branch Build) Processing Project:master
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:219[1417]: INFO Resetting dropped connection: domain.com
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/project/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:219[1417]: INFO Resetting dropped connection: domain.com
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/project/ID/ HTTP/1.1" 200 None
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/version/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/version/ID/ HTTP/1.1" 200 None
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/build/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/build/ID/ HTTP/1.1" 200 None
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "PUT /api/v2/build/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "PUT /api/v2/build/ID/ HTTP/1.1" 400 39
[23/Aug/2019 08:41:46] readthedocs.doc_builder.environments:493[1417]: ERROR Unable to update build: id=ID error={"project":["This field is required."]}
[23/Aug/2019 08:41:46] readthedocs.projects.tasks:111[1417]: INFO (Build) [Project:latest] Updating docs from VCS
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/version/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:46] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/version/ID/ HTTP/1.1" 200 None
[23/Aug/2019 08:41:46] readthedocs.projects.tasks:589[1417]: INFO (Build) [Project:latest] Checking out version latest: master
[23/Aug/2019 08:41:46] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git status
[23/Aug/2019 08:41:46] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: HEAD detached at origin/master
nothing to commit, working directory clean

[23/Aug/2019 08:41:46] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git remote set-url origin https://github.com/company/project.git
[23/Aug/2019 08:41:46] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: 
[23/Aug/2019 08:41:46] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git fetch --tags --prune
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: 
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git show-ref remotes/origin/master
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: REF refs/remotes/origin/master

[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git checkout --force --quiet origin/master
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: 
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git clean -d -f -f
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: 
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git submodule sync
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: 
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git submodule update --init --recursive --force
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: 
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git show-ref --tags
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: 
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git branch -r
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]:   origin/HEAD -> origin/master
  origin/master

[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "POST /api/v2/project/ID/sync_versions/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/project/ID/sync_versions/ HTTP/1.1" 405 40
[23/Aug/2019 08:41:47] readthedocs.projects.tasks:628[1417]: ERROR Sync Versions Exception
Traceback (most recent call last):
  File "/path/to/dir/readthedocs/projects/tasks.py", line 626, in update_imported_docs
    try:
  File "/path/to/dir/python2.7/dist-packages/slumber/__init__.py", line 167, in post
    resp = self._request("POST", data=data, files=files, params=kwargs)
  File "/path/to/dir/python2.7/dist-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
HttpClientError: Client Error 405: http://domain.com/api/v2/project/ID/sync_versions/
[23/Aug/2019 08:41:47] readthedocs.vcs_support.utils:101[1417]: INFO Lock (docs): Releasing
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:62[1417]: INFO VCS[Project:latest]: git rev-parse HEAD
[23/Aug/2019 08:41:47] readthedocs.vcs_support.base:70[1417]: INFO VCS[Project:latest]: REF

[23/Aug/2019 08:41:47] readthedocs.doc_builder.environments:326[1417]: INFO (Build) [Project:latest] Build finished
[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/project/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "GET /api/v2/project/ID/ HTTP/1.1" 200 None
[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "PUT /api/v2/project/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "PUT /api/v2/project/ID/ HTTP/1.1" 400 146
[23/Aug/2019 08:41:47] readthedocs.projects.tasks:159[1417]: ERROR An unhandled exception was raised during build setup
Traceback (most recent call last):
  File "/path/to/dir/readthedocs/projects/tasks.py", line 152, in run
    
  File "/path/to/dir/readthedocs/projects/tasks.py", line 235, in run_setup
    if self.setup_env.successful and not self.project.has_valid_clone:
  File "/path/to/dir/readthedocs/projects/tasks.py", line 368, in set_valid_clone
    project_data['has_valid_clone'] = True
  File "/path/to/dir/python2.7/dist-packages/slumber/__init__.py", line 175, in put
    resp = self._request("PUT", data=data, files=files, params=kwargs)
  File "/path/to/dir/python2.7/dist-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
HttpClientError: Client Error 400: http://domain.com/api/v2/project/ID/
[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "PUT /api/v2/build/ID/ HTTP/1.1" 301 185
[23/Aug/2019 08:41:47] requests.packages.urllib3.connectionpool:350[1417]: DEBUG "PUT /api/v2/build/ID/ HTTP/1.1" 400 39
[23/Aug/2019 08:41:47] readthedocs.doc_builder.environments:493[1417]: ERROR Unable to update build: id=ID error={"project":["This field is required."]}
[23/Aug/2019 08:41:47] celery.app.trace:123[1417]: INFO Task readthedocs.projects.tasks.update_docs[XXX] succeeded in 1.68011067435s: False
[23/Aug/2019 08:41:47] readthedocs.core.views.hooks:47[1417]: INFO (Version build) Building docs:latest
[23/Aug/2019 08:41:47] readthedocs.core.views.hooks:83[1417]: INFO (Branch Build) Processing docs:latest
[23/Aug/2019 08:41:47] readthedocs.core.views.hooks:65[1417]: INFO (Version build) Not Building latest
[23/Aug/2019 08:41:47] readthedocs.restapi.views.integrations:120[1417]: INFO Skipping project branches: project=Project branches=[u'master']
```

**Note:**
Nothing on the server has changed except adding an SSL certificate. Any assistance or even a point in the right direction would be extremely helpful and appreciated.

**Comment by stsewd** [comment]
Looks like you are using python2, Read the Docs only runs on python3.6 https://docs.readthedocs.io/en/latest/changelog.html#version-3-0-0
