### ISSUE TITLE
Elasticsearch auto Index fails

### ISSUE THREAD

**Issue by maldag** [readthedocs/readthedocs.org#6113]
## Details
I'm running a local installation of readthedocs 3.7.2 with the following procedure:

```
$> python3 manage.py reindex_elasticsearch
# Result:
# ERROR Task readthedocs.search.tasks.index_objects_to_es[0f8bb0a9-ee18-4d90-9d14-e1038d12047b] raised unexpected: ValueError('You must pass a chunk or objects_id.',)

$> python3 manage.py runserver 0.0.0.0:8000
# Everything works fine
```
Then I create a project and build the project using the `readthedocs/build:latest` docker image. This is also working. After completion of building the project the elasticsearch-index shall be automatically updated. Thus, I activated the following settings:
```
 @property
        def ES_HOSTS(self):  # noqa
            return [
                '{0}:{1}'.format(
                    os.getenv('ELASTICSEARCH_HOST', 'elasticsearch'),
                    os.getenv('ELASTICSEARCH_PORT', '9200')
                )
            ]

        ELASTICSEARCH_DSL_AUTOSYNC = True
        ELASTICSEARCH_DSL_AUTO_REFRESH = True
        ELASTICSEARCH_DSL={
            'default': {
                'hosts': '{0}:{1}'.format(
                    os.getenv('ELASTICSEARCH_HOST', 'elasticsearch'),
                    os.getenv('ELASTICSEARCH_PORT', '9200')
                )
            },
```

The log message after compiling the docs:
```
readthedocs_1    | readthedocs.doc_builder.environments:142[57]: INFO Running: 'ln -nsf /app/user_builds/<project-name>/rtd-builds/latest /app/public_web_root/<project-name>/de/latest' [/app/readthedocs]
readthedocs_1    | readthedocs.projects.tasks:1791[57]: INFO (Build) [<project-name>:] Updating static metadata
readthedocs_1    | celery.app.trace:124[57]: INFO Task readthedocs.projects.tasks.sync_files[556a142e-a379-42cd-979c-107ac535eb6e] succeeded in 0.1291863530000228s: None
readthedocs_1    | readthedocs.projects.tasks:1357[57]: INFO (Build) [<project-name>:latest] Creating ImportedFiles
readthedocs_1    | readthedocs.search.utils:39[57]: INFO Indexing new objecst into search index for: <project-name>:latest
readthedocs_1    | readthedocs.search.documents:28[57]: INFO Hacking Elastic indexing to fix connection pooling
readthedocs_1    | readthedocs.search.parse_json:87[57]: INFO Unable to index content for: json/<project-name>/latest/genindex.fjson
readthedocs_1    | readthedocs.projects.models:1297[57]: WARNING Unhandled exception during search processing file: json/<project-name>/latest/genindex.fjson
readthedocs_1    | readthedocs.search.parse_json:87[57]: INFO Unable to index content for: json/<project-name>/latest/search.fjson
readthedocs_1    | readthedocs.projects.models:1297[57]: WARNING Unhandled exception during search processing file: json/<project-name>/latest/search.fjson
elasticsearch_1  | [2019-08-28T07:12:13,723][INFO ][o.e.c.m.MetaDataCreateIndexService] [7L19Uoh] [page_index] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
elasticsearch_1  | [2019-08-28T07:12:14,171][INFO ][o.e.c.m.MetaDataMappingService] [7L19Uoh] [page_index/XyQO-TIgR4ONmLdcUTDfRQ] create_mapping [doc]
readthedocs_1    | readthedocs.search.utils:66[57]: INFO Deleting old files from search index for: <project-name>:latest
readthedocs_1    | celery.app.trace:124[57]: INFO Task readthedocs.projects.tasks.sync_callback[244e27b8-11be-4761-95b5-4bf3bb88ce19] succeeded in 1.7548883609999848s: None
readthedocs_1    | readthedocs.doc_builder.environments:891[57]: INFO Removing container: id=build-6-project-2-<project-name>
readthedocs_1    | readthedocs.doc_builder.environments:575[57]: INFO (Build) [<project-name>:latest] Build finished
```
So I'm guessing it's creating the index since it didn't exist.

# Actual problem
Using the search engine in a project doesn't return any results.

# What else did I try yet
I stopped the server and tried to reindex again using
`$> python3 manage.py reindex_elasticsearch`  but this causes the following log message:

```
readthedocs_1    | readthedocs.search.management.commands.reindex_elasticsearch:55[36]: INFO Adding indexing tasks to default queue
elasticsearch_1  | [2019-08-28T07:14:40,579][INFO ][o.e.c.m.MetaDataCreateIndexService] [7L19Uoh] [page_index_20190828071440] creating index, cause [api], templates [], shards [2]/[0], mappings [doc]
readthedocs_1    | elasticsearch:105[36]: INFO PUT http://elasticsearch:9200/page_index_20190828071440 [status:200 request:0.198s]
readthedocs_1    | celery.app.trace:124[36]: INFO Task readthedocs.search.tasks.create_new_es_index[9af7f50f-d639-4fd2-bf1b-a1afc93d98c8] succeeded in 0.20039162700004454s: None
readthedocs_1    | readthedocs.search.tasks:48[36]: INFO Replacing index name page_index_20190828071440 with page_index_20190828071440
readthedocs_1    | readthedocs.search.tasks:50[36]: INFO Indexing model: HTMLFile, '26' objects
readthedocs_1    | readthedocs.search.documents:28[36]: INFO Hacking Elastic indexing to fix connection pooling
readthedocs_1    | readthedocs.search.parse_json:87[36]: INFO Unable to index content for: json/<project-name>/latest/genindex.fjson
readthedocs_1    | readthedocs.projects.models:1297[36]: WARNING Unhandled exception during search processing file: json/<project-name>/latest/genindex.fjson
readthedocs_1    | readthedocs.search.parse_json:87[36]: INFO Unable to index content for: json/<project-name>/latest/search.fjson
readthedocs_1    | readthedocs.projects.models:1297[36]: WARNING Unhandled exception during search processing file: json/<project-name>/latest/search.fjson
readthedocs_1    | elasticsearch:105[36]: INFO POST http://elasticsearch:9200/_bulk?refresh=true [status:200 request:0.283s]
readthedocs_1    | readthedocs.search.tasks:55[36]: INFO Undoing index replacement, settings page_index_20190828071440 with page_index_20190828071440
readthedocs_1    | celery.app.trace:124[36]: INFO Task readthedocs.search.tasks.index_objects_to_es[514b6160-3bbc-4548-ad21-8556980f88b7] succeeded in 0.503753351000114s: None
readthedocs_1    | elasticsearch:105[36]: INFO HEAD http://elasticsearch:9200/page_index [status:200 request:0.008s]
readthedocs_1    | elasticsearch:105[36]: INFO GET http://elasticsearch:9200/page_index [status:200 request:0.003s]
readthedocs_1    | elasticsearch:133[36]: WARNING PUT http://elasticsearch:9200/page_index_20190828071440/_alias/page_index [status:400 request:0.014s]
readthedocs_1    | celery.app.trace:249[36]: ERROR Task readthedocs.search.tasks.switch_es_index[0b90c983-5192-4c01-8d90-1e2f39499158] raised unexpected: RequestError(400, 'invalid_alias_name_exception', {'error': {'root_cause': [{'type': 'invalid_alias_name_exception', 'reason': 'Invalid alias name [page_index], an index exists with the same name as the alias', 'index_uuid': 'XyQO-TIgR4ONmLdcUTDfRQ', 'index': 'page_index'}], 'type': 'invalid_alias_name_exception', 'reason': 'Invalid alias name [page_index], an index exists with the same name as the alias', 'index_uuid': 'XyQO-TIgR4ONmLdcUTDfRQ', 'index': 'page_index'}, 'status': 400})
readthedocs_1    | Traceback (most recent call last):
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
readthedocs_1    |     R = retval = fun(*args, **kwargs)
readthedocs_1    |   File "/app/readthedocs/search/tasks.py", line 100, in switch_es_index
readthedocs_1    |     new_index.put_alias(name=index_name)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 368, in put_alias
readthedocs_1    |     return self.connection.indices.put_alias(index=self._name, **kwargs)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
readthedocs_1    |     return func(*args, params=params, **kwargs)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 428, in put_alias
readthedocs_1    |     "PUT", _make_path(index, "_alias", name), params=params, body=body
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 353, in perform_request
readthedocs_1    |     timeout=timeout,
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 236, in perform_request
readthedocs_1    |     self._raise_error(response.status, raw_data)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 162, in _raise_error
readthedocs_1    |     status_code, error_message, additional_info
readthedocs_1    | elasticsearch.exceptions.RequestError: RequestError(400, 'invalid_alias_name_exception', 'Invalid alias name [page_index], an index exists with the same name as the alias')
readthedocs_1    | Traceback (most recent call last):
readthedocs_1    |   File "manage.py", line 11, in <module>
readthedocs_1    |     execute_from_command_line(sys.argv)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
readthedocs_1    |     utility.execute()
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
readthedocs_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
readthedocs_1    |     self.execute(*args, **cmd_options)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
readthedocs_1    |     output = self.handle(*args, **options)
readthedocs_1    |   File "/app/readthedocs/search/management/commands/reindex_elasticsearch.py", line 140, in handle
readthedocs_1    |     self._run_reindex_tasks(models=models, queue=queue)
readthedocs_1    |   File "/app/readthedocs/search/management/commands/reindex_elasticsearch.py", line 102, in _run_reindex_tasks
readthedocs_1    |     chain(pre_index_task, chord_tasks, missed_index_task).apply_async(**apply_async_kwargs)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/celery/canvas.py", line 564, in apply_async
readthedocs_1    |     return self.apply(args, kwargs, **options)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/celery/canvas.py", line 716, in apply
readthedocs_1    |     last and (last.get(),), **dict(self.options, **options))
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/celery/result.py", line 918, in get
readthedocs_1    |     raise self.result
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
readthedocs_1    |     R = retval = fun(*args, **kwargs)
readthedocs_1    |   File "/app/readthedocs/search/tasks.py", line 100, in switch_es_index
readthedocs_1    |     new_index.put_alias(name=index_name)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 368, in put_alias
readthedocs_1    |     return self.connection.indices.put_alias(index=self._name, **kwargs)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
readthedocs_1    |     return func(*args, params=params, **kwargs)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 428, in put_alias
readthedocs_1    |     "PUT", _make_path(index, "_alias", name), params=params, body=body
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 353, in perform_request
readthedocs_1    |     timeout=timeout,
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 236, in perform_request
readthedocs_1    |     self._raise_error(response.status, raw_data)
readthedocs_1    |   File "/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 162, in _raise_error
readthedocs_1    |     status_code, error_message, additional_info
readthedocs_1    | elasticsearch.exceptions.RequestError: RequestError(400, 'invalid_alias_name_exception', 'Invalid alias name [page_index], an index exists with the same name as the alias')
```

# Workaround

1.  turn off the `ELASTICSEARCH_DSL_*` feature
2.  Create and build a project
3.  Run `$> python3 manage.py reindex_elasticsearch`

# How to properly fix
When running the whole server for the very first time, I'd expected to create an empty index and connect it with the other instances. After that the autosync might work?

**Comment by maldag** [comment]
I've found a proper way for this, using `$> python3 manage.py search_index --create` to create an index in the first place resolves this chicken-egg problem.
Sorry for the noise ...
