### ISSUE TITLE
Failed to import numpydoc

### ISSUE THREAD

**Issue by damon-chem-e** [readthedocs/readthedocs.org#6246]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/byu-finance-library-finance-byu/
* Build URL (if applicable): https://readthedocs.org/projects/byu-finance-library-finance-byu/builds/9762330/
* Read the Docs username (if applicable): damonpetersen

## Expected Result

As stated in the RTD documentation, numpydoc can be loaded by specifying it in the extensions in conf.py, which I have done: 

`extensions = ['sphinx.ext.autodoc','numpydoc']`

## Actual Result

RTD is failing to import the numpydoc extension. This project builds fine locally. 

```
python /home/docs/checkouts/readthedocs.org/user_builds/byu-finance-library-finance-byu/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/byu-finance-library-finance-byu/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'numpydoc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/byu-finance-library-finance-byu/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/byu-finance-library-finance-byu/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/byu-finance-library-finance-byu/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/byu-finance-library-finance-byu/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension numpydoc (exception: No module named 'numpydoc')

Extension error:
Could not import extension numpydoc (exception: No module named 'numpydoc')
```

**Comment by stsewd** [comment]
> As stated in the RTD documentation, numpydoc can be loaded by specifying it in the extensions in conf.py, which I have done:

Can you please link me to that?

You need to tell to rtd to install that dependency too, check https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#specifying-dependencies

**Comment by damon-chem-e** [comment]
https://docs.readthedocs.io/en/stable/faq.html#does-read-the-docs-work-well-with-legible-docstrings

**Comment by damon-chem-e** [comment]
I specified the requirements file, but RTD is not building the documentation for the class. Again, this builds perfectly locally. 

contents.rst:
```
.. Finance Library documentation master file, created by
   sphinx-quickstart on Sun Sep 29 13:40:47 2019.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Finance Library Documentation
===========================================

This library will contains functions and classes useful for finance research at Brigham 
Young University. 

The library can currently be installed from the Test PyPi server:: 
    
    pip install -i https://test.pypi.org/simple/ finance-byu

To use this library, use the following code at the top of your script: :code:`import 
finance_byu as fin`. Currently the only available module is the :code:`fin.regtables` module which contains the 
:code:`Regtable` class. This class can be accessed via :code:`from finance_byu.regtables import Regtable`.

.. toctree::
   :maxdepth: 2
   :caption: Contents:
   
.. autoclass:: finance_byu.regtables.Regtable
   



Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
```

**Comment by stsewd** [comment]
```
WARNING: autodoc: failed to import class 'regtables.Regtable' from module 'finance_byu'; the following exception was raised:
No module named 'numpy'
```

That's from the build output, it builds locally for you because you have all the requirements from your project installed, you need to specify the same requirements on read the docs.

**Comment by damon-chem-e** [comment]
Thank you for your help! Looks like it is building fine now.
