### ISSUE TITLE
Build failing on same commit that passed 4 weeks ago

### ISSUE THREAD

**Issue by swainn** [readthedocs/readthedocs.org#6359]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/tethys-platform/
* Build URL (if applicable): https://readthedocs.org/projects/tethys-platform/builds/9927212/
* Read the Docs username (if applicable): swainn

## Expected Result

The docs build to pass.

## Actual Result

The docs build failed.

Failed Build: https://readthedocs.org/projects/tethys-platform/builds/9927212/
Last Pass (~ 4 weeks ago): https://readthedocs.org/projects/tethys-platform/builds/9790025/

Both builds are pulling at the same commit (https://github.com/tethysplatform/tethys/commit/f423488647973bec42199c47a1b4e465ebab6bb9)

The error is:

```
Running Sphinx v2.2.1
NOTE: The following modules are mocked to prevent timeouts during the docs build process on RTD:
bokeh, bokeh.core.templates, bokeh.document, bokeh.embed, bokeh.embed.elements, bokeh.embed.util, bokeh.resources, bokeh.server.django, bokeh.server.django.consumers, bokeh.util.compiler, channels, conda, conda.cli, conda.cli.python_api, condorpy, django_gravatar, dask, dask.delayed, dask.distributed, distributed, distributed.protocol, distributed.protocol.serialize, distro, docker, docker.types, docker.errors, guardian, guardian.admin, model_utils, model_utils.managers, plotly, plotly.offline, social_core, social_core.exceptions, social_django, sqlalchemy, sqlalchemy.orm, tethys_apps.harvester, tethys_compute.utilities, yaml
master
loading translations [en]... done
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 269, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 329, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest/lib/python3.6/site-packages/sphinx/builders/html.py", line 249, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest/lib/python3.6/site-packages/sphinx/builders/html.py", line 289, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest/lib/python3.6/site-packages/sphinx/theming.py", line 263, in create
    '(missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_materialdesign_theme' found (missing theme.conf?)

Theme error:
no theme named 'sphinx_materialdesign_theme' found (missing theme.conf?)
```

However, the theme is successfully installed when the conda environment is created:

```
Collecting package metadata: ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Ran pip subprocess with arguments:
[u'/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/checkouts/latest/docs/tmpM9grt3.requirements.txt']
Pip subprocess output:
Collecting sphinx_materialdesign_theme
  Downloading https://files.pythonhosted.org/packages/6e/c4/0794bb6fc0bfae83b4f4b34e0784bf1553972560f04eb0cb701a3c200e86/sphinx_materialdesign_theme-0.1.11.tar.gz (18.0MB)
Building wheels for collected packages: sphinx-materialdesign-theme
  Building wheel for sphinx-materialdesign-theme (setup.py): started
  Building wheel for sphinx-materialdesign-theme (setup.py): finished with status 'done'
  Created wheel for sphinx-materialdesign-theme: filename=sphinx_materialdesign_theme-0.1.11-cp38-none-any.whl size=18258718 sha256=8b09234f873f60c55720f1de1513e2aea89efc62a54bb915ab17311cfa5a90c1
  Stored in directory: /home/docs/.cache/pip/wheels/3b/88/ca/c0fb278fbb4785b40e517f79d6cabbbc4699a85741b674d0ee
Successfully built sphinx-materialdesign-theme
Installing collected packages: sphinx-materialdesign-theme
Successfully installed sphinx-materialdesign-theme-0.1.11
```

**Comment by stsewd** [comment]
I can see that the sphinx version is different, also, you don't have pinned dependencies, so an update on those may broke the build https://github.com/tethysplatform/tethys/blob/f423488647973bec42199c47a1b4e465ebab6bb9/docs/docs_environment.yml#L13-L23

Please try building the documentation locally, it doesn't look like a read the docs problem.

**Comment by swainn** [comment]
@stsewd thank you for the quick reply. I just rebuilt locally with a new conda environment and it worked without issue. 

The version of the sphinx-materialdesign-theme that is says it can't find is the same in both the passing and failing build (0.1.11).

As far as I can tell the only version that changed is sphinx (2.2.0 to 2.2.1). But I tried a build with the sphinx version pinned to 2.2.0 and it didn't work either.

Is it possible that RTD isn't using the conda environment?

**Comment by swainn** [comment]
I pinned the python version to 3.7 in my conda environment and in the .readthedocs.yml. 

Upon closer inspection, it looked like the conda environment was trying to resolve packages for Python 3.8, but ended up installing Python 3.6 packages during the `conda install --yes --quiet --name latest mock pillow sphinx` step???:

```
conda install --yes --quiet --name latest mock pillow sphinx sphinx_rtd_theme
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/docs/checkouts/readthedocs.org/user_builds/tethys-platform/conda/latest

  added / updated specs:
    - mock
    - pillow
    - sphinx
    - sphinx_rtd_theme


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.8.28  |                0         132 KB
    certifi-2019.9.11          |           py37_0         154 KB
    freetype-2.9.1             |       h8a8886c_1         822 KB
    jpeg-9b                    |       h024ee3a_2         248 KB
    libpng-1.6.37              |       hbc83047_0         364 KB
    libtiff-4.0.10             |       h2733197_2         604 KB
    mock-3.0.5                 |           py37_0          47 KB
    olefile-0.46               |           py37_0          48 KB
    openssl-1.1.1d             |       h7b6447c_2         3.7 MB
    pillow-6.2.0               |   py37h34e0f95_0         643 KB
    sphinx-2.2.0               |             py_0         1.5 MB
    sphinx_rtd_theme-0.4.3     |             py_0         5.1 MB
    zstd-1.3.7                 |       h0b5b093_0         887 KB
    ------------------------------------------------------------
                                           Total:        14.2 MB

The following NEW packages will be INSTALLED:

  freetype           pkgs/main/linux-64::freetype-2.9.1-h8a8886c_1
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libtiff            pkgs/main/linux-64::libtiff-4.0.10-h2733197_2
  mock               pkgs/main/linux-64::mock-3.0.5-py37_0
  olefile            pkgs/main/linux-64::olefile-0.46-py37_0
  pillow             pkgs/main/linux-64::pillow-6.2.0-py37h34e0f95_0
  sphinx_rtd_theme   pkgs/main/noarch::sphinx_rtd_theme-0.4.3-py_0
  zstd               pkgs/main/linux-64::zstd-1.3.7-h0b5b093_0

The following packages will be UPDATED:

  openssl            conda-forge::openssl-1.1.1c-h516909a_0 --> pkgs/main::openssl-1.1.1d-h7b6447c_2

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2019.9.1~ --> pkgs/main::ca-certificates-2019.8.28-0
  certifi                                       conda-forge --> pkgs/main
  sphinx                                        conda-forge --> pkgs/main


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Command time: 34s Return: 0
```
