### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by harshit2608** [readthedocs/readthedocs.org#6386]
BELOW IS THE BUILDING ERROR OUTPUT

Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [ 16%] docguide/indexdoc
reading sources... [ 33%] getting_started/editor/index
reading sources... [ 50%] getting_started/scripting/index
reading sources... [ 66%] getting_started/step_by_step/index
reading sources... [ 83%] getting_started/workflow/index
reading sources... [100%] index

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/stupefy-docs/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stupefy-docs/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/stupefy-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/stupefy-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/stupefy-docs/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 472, in read
    self.env.doc2path(self.config.master_doc))
sphinx.errors.SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/stupefy-docs/checkouts/latest/docs/contents.rst not found

Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/stupefy-docs/checkouts/latest/docs/contents.rst not found

I tried to solve this but can't seem to find any answers .
It always show this error even after following the readthedocs official tutorial

**Comment by stsewd** [comment]
Please follow the issue template when reporting a failure.

**Comment by harshit2608** [comment]
> Please follow the issue template when reporting a failure.

Thnx for reply , but after adding this line ( master_doc = 'index' ) in conf.py it worked
