### ISSUE TITLE
Build fails after restructuring

### ISSUE THREAD

**Issue by fwitte** [readthedocs/readthedocs.org#6413]
Hey everybody,

I hope someone can help with my issue (if I am allowed to post this here): Currently I am restructuring my python package ([oemof/tespy](https://github.com/oemof/tespy/tree/fix/doc_tests)) and wanted to build one of the branches (fix/doc_tests) as latest. But the build always fails due sphinx missing out on the tespy.networks module. I already confirmed that the software version on this branch runs well not only on my machine but also on others. The build on this specific branch has yet never been successful.

```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tespy/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tespy/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tespy/checkouts/latest/doc/conf.py", line 17, in <module>
    import tespy
  File "/home/docs/checkouts/readthedocs.org/user_builds/tespy/envs/latest/lib/python3.7/site-packages/TESPy-0.2.0.dev0-py3.7.egg/tespy/__init__.py", line 6, in <module>
    from tespy.networks import networks, network_reader
ModuleNotFoundError: No module named 'tespy.networks'
```

## Details

* Read the Docs project URL: https://readthedocs.org/projects/tespy
* Build URL (if applicable): Available but an older version.
* Read the Docs username (if applicable): fwitte

## Expected Result

Build of the branch should not fail due to the ModuleNotFoundError as all modules work.

## Actual Result

Well, the build failed.

Does somebody have a hint, of what I may be doing wrong? Thank you very much, have a nice wednesday/thursday :).

**Comment by stsewd** [comment]
Isn't missing networks here https://github.com/oemof/tespy/blob/3e0cff70c60ddc03ac18c12bb4f664da7c6dfe49/setup.py#L17?

**Comment by fwitte** [comment]
> Isn't missing networks here https://github.com/oemof/tespy/blob/3e0cff70c60ddc03ac18c12bb4f664da7c6dfe49/setup.py#L17?

Wow, that was very fast. I think I'll need to drop work for today...
Thank you so much, oversaw that! Closing the issue.
