### ISSUE TITLE
Build fails to clone repo when behind a proxy (as of 3.11.3)

### ISSUE THREAD

**Issue by adamsteinbok** [readthedocs/readthedocs.org#6577]
My environment requires that I make requests to github via a http proxy. Up until `3.11.2`, the build respected the `http_proxy` environment variable set on my host. As of `3.11.3` this variable no longer seems to be respected. 

e.g The following error is thrown when trying to build `https://github.com/rtfd/readthedocs.org`:

```
readthedocs.doc_builder.environments:140[17]: INFO Running: 'git clone --no-single-branch --depth 50 https://github.com/rtfd/readthedocs.org .' [/www/readthedocs.org/user_builds/read-the-docs/checkouts/latest]
[23/Jan/2020 16:31:45] readthedocs.projects.tasks:701[17]: WARNING There was an error with the repository
Traceback (most recent call last):
  File "/www/readthedocs.org/readthedocs/vcs_support/base.py", line 104, in run
    build_cmd = self.environment.run(*cmd, **kwargs)
  File "/www/readthedocs.org/readthedocs/doc_builder/environments.py", line 628, in run
    return super().run(*cmd, **kwargs)
  File "/www/readthedocs.org/readthedocs/doc_builder/environments.py", line 414, in run
    return self.run_command_class(cls=self.command_class, cmd=cmd, **kwargs)
  File "/www/readthedocs.org/readthedocs/doc_builder/environments.py", line 634, in run_command_class
    return super().run_command_class(*cmd, **kwargs)
  File "/www/readthedocs.org/readthedocs/doc_builder/environments.py", line 486, in run_command_class
    raise BuildEnvironmentWarning(msg)
readthedocs.doc_builder.exceptions.BuildEnvironmentWarning: Command git clone --no-single-branch --depth 50 https://github.com/rtfd/readthedocs.org . failed:
Cloning into '.'...
fatal: unable to access 'https://github.com/rtfd/readthedocs.org/': Failed to connect to github.com port 443: Connection refused
```

I had a quick look at the commit history and this seems to me to be related to changes made in #6482. 

Is there a way to specify a proxy now that host environment variables are no longer passed to the build?

**Comment by stsewd** [comment]
Are you using docker?

https://github.com/readthedocs/readthedocs.org/blob/cd7265f65f38d6be8ed790654bea4bc95db93c74/readthedocs/settings/base.py#L349-L350

**Comment by adamsteinbok** [comment]
Ah, I should have mentioned, this issue occurs in both the docker and local build environments.

**Comment by humitos** [comment]
I think this is because we stopped passing _all the environment variables_ in this line https://github.com/readthedocs/readthedocs.org/pull/6482/files#r363697639 and we start passing just the ones _we_ needed.

**Comment by stsewd** [comment]
All env vars are passed if we don't set any when creating the build environment. I think we can use https://docs.readthedocs.io/en/stable/guides/environment-variables.html in cases like this. We only need to expose those env vars on the clone step too (currently we only expose them in the build step).

**Comment by adamsteinbok** [comment]
I see this issue has been automatically marked stale. As far as I can tell, as of 4.1.1 it has not been resolved. Is there any plan to fix this issue? Can anyone suggest a workaround?

**Comment by stsewd** [comment]
A solution I can see here is to pass env variables in the clone step, not only on the build step. That requires a design decision before implementing it.

**Comment by adamsteinbok** [comment]
@stsewd Thanks for the update and for re-opening :)

**Comment by humitos** [comment]
Hi @adamsteinbok! We do not offer support for custom installation. Please read our philosophy at https://docs.readthedocs.io/en/stable/open-source-philosophy.html

Unfortunately, the core team won't be able to help you on this issue. I'm closing it for now and we can revisit in the future if we hit it.
