### ISSUE TITLE
ImportError: cannot import name 'PackageFinder' build error

### ISSUE THREAD

**Issue by stanislaw** [readthedocs/readthedocs.org#6586]
## Details

* Read the Docs project URL: https://filecheck.readthedocs.io/en/latest
* Build URL (if applicable): https://readthedocs.org/projects/filecheck/builds/10333035/
* Read the Docs username (if applicable): `stanislawpankevich`

## Expected Result

The docs get deployed to the https://filecheck.readthedocs.io/en/latest/ when I merge commits to master. The repo: https://github.com/stanislaw/FileCheck.py.

## Actual Result

The docs cannot be deployed because of the build error:

```
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.5.7/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.5.7/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/filecheck/envs/latest/lib/python3.5/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/filecheck/envs/latest/lib/python3.5/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/docs/checkouts/readthedocs.org/user_builds/filecheck/envs/latest/lib/python3.5/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/filecheck/envs/latest/lib/python3.5/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/filecheck/envs/latest/lib/python3.5/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/home/docs/checkouts/readthedocs.org/user_builds/filecheck/envs/latest/lib/python3.5/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/home/docs/checkouts/readthedocs.org/user_builds/filecheck/envs/latest/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 25, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder'
```

**Comment by stanislaw** [comment]
I would like to add that it started happening ~20 hours ago:

```

Failed version latest (html)29 minutes ago
Failed version latest (html)11 hours, 15 minutes ago
Failed version latest (html)15 hours, 34 minutes ago
Failed version latest (html)17 hours, 32 minutes ago
Failed version latest (html)17 hours, 50 minutes ago
Failed version latest (html)18 hours, 23 minutes ago
Failed version latest (html)18 hours, 27 minutes ago
Failed version latest (html)19 hours, 49 minutes ago
Failed version latest (html)20 hours, 2 minutes ago
Passed version latest (html)20 hours, 48 minutes ago
Passed version latest (html)1 day, 10 hours ago
Passed version latest (html)1 day, 19 hours ago
...
```

**Comment by humitos** [comment]
Hi! Can you take a look at https://github.com/readthedocs/readthedocs.org/issues/6566, please? It seems it's duplicated.
