### ISSUE TITLE
Conflicts with project own Jinja2 version (TemplateAssertionError: no filter named 'tojson')

### ISSUE THREAD

**Issue by amercader** [readthedocs/readthedocs.org#6894]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ckan
* Build URL (if applicable): https://readthedocs.org/projects/ckan/builds/10825104/
* Read the Docs username (if applicable):

A version from our project has a `Jinja2==2.8` requirement, and that seems to cause a conflict with internal RTD tooling:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 333, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 431, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 440, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/html.py", line 607, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/builders/html.py", line 1013, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/readthedocs_ext/readthedocs.py", line 126, in rtd_render
    rtd_content = app.builder.templates.render_string(templ, template_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 199, in render_string
    return self.environment.from_string(source).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ckan/envs/2.8/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 25, in template
TemplateAssertionError: no filter named 'tojson'
```

Our docs or source code doesn't use this filter at all, and from the stack trace you can tell that the exception originates from one of the RTD libraries. My first attemp was to downgrade `readthedocs-sphinx-ext` to 0.6.0 to avoid the Jinja2>=2.9 requirement:

```
ERROR: readthedocs-sphinx-ext 1.0.1 has requirement Jinja2>=2.9, but you'll have jinja2 2.8 which is incompatible.
```

That seemed to help as the warning was gone and after installing our requirements it appears Jinja2 2.8 is the one installed. But we are still getting the same exception.
Is there another library that we could pin to avoid this dependency?

## Expected Result

Docs are built on a project that requires Jinja2==2.8

## Actual Result

Build fails with the exception above.

**Comment by humitos** [comment]
> A version from our project has a `Jinja2==2.8` requirement, and that seems to cause a conflict with internal RTD tooling:

Do you need jinja2 to build your docs? You may not need to install it. Taking a quick look at your repo, you may not need to install a lot of packages that you are installing currently just to build the docs.

BTW, jinja2==2.8 is deprecated.

**Comment by amercader** [comment]
Thanks @humitos. IIRC we need to install the project requirements to be able to extract the docstrings but I'll double check this.

**Comment by humitos** [comment]
@amercader I see. If you are using `autodoc` sphinx extension, you need to install requirements, yes. Another option could be to use [`sphinx-autoapi`](https://sphinx-autoapi.readthedocs.io/) that does exactly the same as `autodoc` but statically --no dependencies are required to be installed.

**Comment by amercader** [comment]
Interesting, thanks @humitos will check sphinx-autoapi for sure
