### ISSUE TITLE
Build fails with "fatal: not a git repository (or any of the parent directories): .git"

### ISSUE THREAD

**Issue by rlenain** [readthedocs/readthedocs.org#7088]
## Details

* Read the Docs project URL: `https://readthedocs.org/projects/surfboard/`
* Build URL (if applicable): `https://readthedocs.org/projects/surfboard/builds/11062847/`
* Read the Docs username (if applicable): `raphnovoic`

## Expected Result

*A description of what you wanted to happen*: I am running a build on my project. It must be installed (so I have activated the trigger `setup.py install` option in the advanced options). I am expecting for the package to install fine and build the documentation.

## Actual Result

*A description of what actually happened*

The install goes fine initially, but fails on an external package `pysptk` with the following error: `fatal: not a git repository (or any of the parent directories): .git` which does not make any sense to me? I can also assure that the build works fine locally. Here is the error:

```Installed /home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/PeakUtils-1.3.3-py3.7.egg
Searching for pysptk==0.1.18
Reading https://pypi.org/simple/pysptk/
Downloading https://files.pythonhosted.org/packages/7c/25/4ea0932fbf0f1db42934b85011c1c825bcf57055ecde7e511f05e9fb9197/pysptk-0.1.18.tar.gz#sha256=34c5ccc40c9e177cfd764daa9f7635c4c1e648e14ce78ba975537dae5a14c4e4
Best match: pysptk 0.1.18
Processing pysptk-0.1.18.tar.gz
Writing /tmp/easy_install-x00vsruw/pysptk-0.1.18/setup.cfg
Running pysptk-0.1.18/setup.py -q bdist_egg --dist-dir /tmp/easy_install-x00vsruw/pysptk-0.1.18/egg-dist-tmp-mk3n2z_u
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-x00vsruw/pysptk-0.1.18/setup.py", line 173, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/home/docs/checkouts/readthedocs.org/user_builds/surfboard/envs/latest/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-x00vsruw/pysptk-0.1.18/setup.py", line 38, in finalize_options
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

**Comment by rlenain** [comment]
Fixed with this: https://github.com/r9y9/pysptk/issues/76
