### ISSUE TITLE
Celery ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by mluds** [readthedocs/readthedocs.org#7105]
## Details

I have a local readthedocs install and get a ValueError exception when trying to import a project. I'm on release 5.1.0, running python 3.6 on Debian buster with celery 4.1.1 (from the requirements files).

## Expected Result

No errors, and the project imports and builds successfully.

## Actual Result

From the debug.log:
```
[19/May/2020 23:31:11] celery.app.trace:124[24]: INFO Task readthedocs.projects.tasks.send_notifications[39551573-cfe1-46c1-b7e2-28bde20fd962] succeeded in 0.005342413205653429s: None
[19/May/2020 23:31:11] celery.app.trace:124[24]: INFO Task readthedocs.oauth.tasks.attach_webhook[119bed10-cacc-450c-bd51-822e96faffd7] succeeded in 0.016763793770223856s: False
[19/May/2020 23:31:11] celery.app.trace:249[24]: ERROR Task readthedocs.projects.tasks.update_docs_task[b6c22791-f1c6-4ddb-b64a-68d141580c30] raised unexpected: ValueError('signal only works in main thread',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/readthedocs.org/readthedocs/projects/tasks.py", line 448, in update_docs_task
    signal.signal(signal.SIGTERM, sigterm_received)
  File "/usr/local/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

I'm using manage.py runserver to run readthedocs, so I tried the `--noreload` option which has no effect, and the `--nothreading` option, which causes pages to hang forever.

**Comment by humitos** [comment]
Hi! Unfortunately, Read the Docs does not offer support for custom installations. Please, read [our philosophy](https://docs.readthedocs.io/en/stable/open-source-philosophy.html) for more information about this.

In case you are not using Docker Compose already for your Read the Docs instance, you may want to take a look at [this guide](https://docs.readthedocs.io/en/stable/development/standards.html) that goes through its setup and configure all the connections between the servers.

The _core team_ does not have the time and resources to help you debugging this. You can find help on sites like StackOverflow tagged as [read-the-docs](https://stackoverflow.com/questions/tagged/read-the-docs). Thanks!

**Comment by pshyms** [comment]
hello, @mluds, did you resolve the problem？ I have the same problem.

**Comment by mluds** [comment]
@pshyms Yes, see here: https://stackoverflow.com/questions/61939886/read-the-docs-local-install-celery-valueerror-signal-only-works-in-main-thread

**Comment by pshyms** [comment]
@mluds hello mluds, thanks for your sharing and it solve the problem.  now i can build successful, but when i read the document, it shows 404 on the website. Do you have any suggestion?  Much appreciated.

 
![image](https://user-images.githubusercontent.com/28621860/96994231-ff580600-155e-11eb-93d8-92d1538c238b.png)
