### ISSUE TITLE
Build failing due to syntax error after minor textual change

### ISSUE THREAD

**Issue by sanity** [readthedocs/readthedocs.org#7577]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/kweb-docs/
* Build URL (if applicable): https://readthedocs.org/projects/kweb-docs/builds/11965157/
* Read the Docs username (if applicable): sanity

## Expected Result

The project should build.

## Actual Result

The build fails with the following error:

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinxcontrib/mermaid.py", line 33, in <module>
    from .autoclassdiag import class_diagram
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinxcontrib/autoclassdiag.py", line 6
    def get_classes(*cls_or_modules, strict=False):
                                          ^
SyntaxError: invalid syntax

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinxcontrib/mermaid.py", line 33, in <module>
    from .autoclassdiag import class_diagram
  File "/home/docs/checkouts/readthedocs.org/user_builds/kweb-docs/envs/latest/lib/python2.7/site-packages/sphinxcontrib/autoclassdiag.py", line 6
    def get_classes(*cls_or_modules, strict=False):
                                          ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-zmRcYw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The previous build succeeded, yet I can't see how the minor text change between the failing build and the build before it could have caused the problem: https://github.com/kwebio/kweb-docs/commit/30db05e15391be97a00206af0ce01168794ac095

Help would be greatly appreciated.

**Comment by sanity** [comment]
Was able to fix the problem by adding [.readthedocs.yml](https://github.com/kwebio/kweb-docs/blob/master/.readthedocs.yml).
