### ISSUE TITLE
Error in installing dependencies for build

### ISSUE THREAD

**Issue by singingwolfboy** [readthedocs/readthedocs.org#7616]
## Details

* Read the Docs project URL: https://flask-dance.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/flask-dance/builds/12215097/
* Read the Docs username (if applicable): singingwolfboy

## Expected Result

Documentation should build successfully.

## Actual Result

There is an error on installing dependencies:

<details>

```
$ /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/bin/python -m pip install --use-feature 2020-resolver --exists-action=w --no-cache-dir -r docs/requirements.txt
Requirement already satisfied: sphinx>=1.3 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from -r docs/requirements.txt (line 1)) (1.8.5)
Requirement already satisfied: snowballstemmer>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: requests>=2.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: Pygments>=2.0 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.7.2)
Requirement already satisfied: imagesize in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: sphinxcontrib-websupport in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.2.4)
Requirement already satisfied: docutils>=0.11 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (0.14)
Requirement already satisfied: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (41.0.1)
Requirement already satisfied: six>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: packaging in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (20.4)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (0.7.12)
Requirement already satisfied: Jinja2>=2.3 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.11.2)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.8.0)
Collecting sphinxcontrib-seqdiag
  Downloading sphinxcontrib_seqdiag-2.0.0-py2.py3-none-any.whl (6.9 kB)
Collecting sphinx>=1.3
  Downloading Sphinx-3.2.1-py3-none-any.whl (2.9 MB)
Requirement already satisfied: snowballstemmer>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: requests>=2.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: Pygments>=2.0 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.7.2)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.8.0)
Requirement already satisfied: imagesize in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: docutils>=0.11 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (0.14)
Requirement already satisfied: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (41.0.1)
Requirement already satisfied: packaging in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (20.4)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (0.7.12)
Requirement already satisfied: sphinxcontrib-serializinghtml in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.1.4)
Requirement already satisfied: Jinja2>=2.3 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.11.2)
Collecting sphinxcontrib-spelling
  Downloading sphinxcontrib_spelling-7.0.0-py3-none-any.whl (14 kB)
Collecting Flask-Sphinx-Themes
  Downloading Flask_Sphinx_Themes-1.0.2-py2.py3-none-any.whl (13 kB)
Collecting sqlalchemy>=0.9
  Downloading SQLAlchemy-1.3.20-cp37-cp37m-manylinux2010_x86_64.whl (1.3 MB)
Collecting sqlalchemy-utils
  Downloading SQLAlchemy-Utils-0.36.8.tar.gz (138 kB)
Requirement already satisfied: six>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.15.0)
Collecting pytest
  Downloading pytest-6.1.2-py3-none-any.whl (272 kB)
Requirement already satisfied: packaging in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (20.4)
Collecting betamax
  Downloading betamax-0.8.1-py2.py3-none-any.whl (39 kB)
Requirement already satisfied: requests>=2.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx>=1.3->-r docs/requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from requests>=2.0.0->sphinx>=1.3->-r docs/requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: sphinxcontrib-serializinghtml in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.1.4)
Requirement already satisfied: six>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from packaging->sphinx>=1.3->-r docs/requirements.txt (line 1)) (2.4.7)
Requirement already satisfied: MarkupSafe>=0.23 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from Jinja2>=2.3->sphinx>=1.3->-r docs/requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: pytz>=2015.7 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx>=1.3->-r docs/requirements.txt (line 1)) (2020.1)
Collecting seqdiag>=0.9.3
  Downloading seqdiag-2.0.0-py3-none-any.whl (2.6 MB)
Collecting blockdiag>=1.5.0
  Downloading blockdiag-2.0.1-py3-none-any.whl (2.7 MB)
Requirement already satisfied: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from sphinx>=1.3->-r docs/requirements.txt (line 1)) (41.0.1)
Requirement already satisfied: Pillow>3.0 in /home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages (from blockdiag>=1.5.0->sphinxcontrib-seqdiag->-r docs/requirements.txt (line 2)) (5.4.1)
Collecting sphinxcontrib-applehelp
  Downloading sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting sphinxcontrib-jsmath
  Downloading sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting sphinxcontrib-devhelp
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting sphinxcontrib-qthelp
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Collecting sphinxcontrib-htmlhelp
  Downloading sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl (96 kB)
Collecting importlib-metadata>=1.7.0
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting PyEnchant>=3.1.1
  Downloading pyenchant-3.1.1-py3-none-any.whl (55 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Collecting toml
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting py>=1.8.2
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting webcolors
  Downloading webcolors-1.11.1-py3-none-any.whl (9.9 kB)
Collecting funcparserlib
  Downloading funcparserlib-0.3.6.tar.gz (30 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Building wheels for collected packages: sqlalchemy-utils, funcparserlib
  Building wheel for sqlalchemy-utils (setup.py): started
  Building wheel for sqlalchemy-utils (setup.py): finished with status 'done'
  Created wheel for sqlalchemy-utils: filename=SQLAlchemy_Utils-0.36.8-py2.py3-none-any.whl size=93219 sha256=a6ee94cbbe35f982328045e1e34010e8650015075595e06ed5e832855d0bdafb
  Stored in directory: /tmp/pip-ephem-wheel-cache-l2m1ytij/wheels/29/c3/6b/495f824c202b91e5dc231e802afa062910f229ad2131588a96
  Building wheel for funcparserlib (setup.py): started
  Building wheel for funcparserlib (setup.py): finished with status 'done'
  Created wheel for funcparserlib: filename=funcparserlib-0.3.6-py3-none-any.whl size=17449 sha256=a7ee4f9d0dd919883468bd2550da2fdb057ea1f826604e9df58c16a3d002ac68
  Stored in directory: /tmp/pip-ephem-wheel-cache-l2m1ytij/wheels/42/c8/37/719a75782f94f905980c739a43b6b451fa76d2aac7c789ce27
Successfully built sqlalchemy-utils funcparserlib
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 191, in get_installation_order
    weights = get_topological_weights(graph)
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 242, in get_topological_weights
    assert len(weights) == len(graph)
AssertionError
```

</details>

I was not able to reproduce this error locally. I suspect it may have something to do with the `--use-feature 2020-resolver` flag, although I'm not sure. I will report this error to the Pip team, but I figured I should also report it to ReadTheDocs.

**Comment by stsewd** [comment]
Yeah, looks like this is the same as https://github.com/readthedocs/readthedocs.org/issues/7605. I'll remove your project from the sample using the new resolver.

**Comment by stsewd** [comment]
I have removed your project from the sample https://readthedocs.org/projects/flask-dance/builds/12220265/
