### ISSUE TITLE
ModuleNotFoundError on build

### ISSUE THREAD

**Issue by Arthurdw** [readthedocs/readthedocs.org#7686]
## Details

I tried building my docs for my project, yet this fails with a ModuleNotFoundError

[My conf file](https://github.com/Arthurdw/dblstats/blob/master/docs/source/conf.py)
[Build url](https://readthedocs.org/projects/dblstats/builds/12387567/)

## Expected Result

A successful build

## Actual Result

The following error:
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/dblstats/checkouts/latest
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/dblstats/envs/latest/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zqta2mo8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zqta2mo8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jfgx9txi
         cwd: /tmp/pip-req-build-zqta2mo8/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zqta2mo8/setup.py", line 4, in <module>
        from dblstats import __version__
      File "/tmp/pip-req-build-zqta2mo8/dblstats/__init__.py", line 22, in <module>
        from .objects import exceptions
      File "/tmp/pip-req-build-zqta2mo8/dblstats/objects/__init__.py", line 21, in <module>
        from .bot import *
      File "/tmp/pip-req-build-zqta2mo8/dblstats/objects/bot.py", line 22, in <module>
        from ..utils import represents
      File "/tmp/pip-req-build-zqta2mo8/dblstats/utils/__init__.py", line 19, in <module>
        from .async_fetcher import AsyncFetcher
      File "/tmp/pip-req-build-zqta2mo8/dblstats/utils/async_fetcher.py", line 21, in <module>
        import aiohttp
    ModuleNotFoundError: No module named 'aiohttp'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by swaldhoer** [comment]
see #7663

**Comment by stsewd** [comment]
The error is happening on the installation of your package, this is because you are importing this file https://github.com/Arthurdw/dblstats/blob/master/dblstats/__init__.py from your setup.py file, that means that it will try to import `aiohttp` before the installation happens. You'll see the same problem locally when trying to install the package in a clean environment. A solution would be to set the version manually or avoid importing other modules in your init file.
