### ISSUE TITLE
Build failed: No module named 'six'

### ISSUE THREAD

**Issue by Jonas231** [readthedocs/readthedocs.org#7709]
## Details

* Read the Docs project URL:
https://readthedocs.org/projects/kdp-doc/

* Build URL (if applicable):
https://readthedocs.org/projects/kdp-doc/builds/12445903/

* Read the Docs username (if applicable):
Jonas231

## Expected Result

I wanted to build a documentation. I am using PyCharm and Sphinx. It is very simple. I just used the 
'sphinx-quickstart' to check if it works. I have a conf.py in directory "source". I have html files in directory 'build/html'. Six is installed in my anaconda virtual environment (in Pycharm: "External Libraries < Python 3.8.

## Actual Result

I get this error message:

Running Sphinx v3.3.1

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kdp-doc/envs/latest/lib/python3.8/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kdp-doc/envs/latest/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kdp-doc/checkouts/latest/docs/conf.py", line 21, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'

**Comment by Arthurdw** [comment]
Same issue as #7705

**Comment by humitos** [comment]
Closing as duplicated. Please subscribe at #7705, thanks!
