### ISSUE TITLE
Build error with build id#12703930

### ISSUE THREAD

**Issue by morcuended** [readthedocs/readthedocs.org#7804]
## Details:

* Project URL: https://lstosa.readthedocs.io
* Build URL(if applicable): https://readthedocs.org/projects/lstosa/builds/12703930/
* Read the Docs username(if applicable): morcuende

## Expected Result

Deploy and host successfully the documentation pages using sphinx and read the docs. I can build the HTML pages locally and with the GitLab CI docs deployment but it does not work when ReadTheDocs tries to build the page.

## Actual Result

```
Running Sphinx v3.4.2
loading translations [en]... done
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx_automodapi/automodsumm.py", line 256, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx_automodapi/automodsumm.py", line 330, in automodsumm_to_autosummary_lines
    filestr = automodapi.automodapi_replace(fr.read(), app, True, docname, False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx_automodapi/automodapi.py", line 294, in automodapi_replace
    modnm, toskip, onlylocals=onlylocals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx_automodapi/automodapi.py", line 405, in _mod_info
    for localnm, fqnm, obj in zip(*find_mod_objs(modname, onlylocals=onlylocals)):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx_automodapi/utils.py", line 81, in find_mod_objs
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/checkouts/latest/osa/scripts/calibrationsequence.py", line 12, in <module>
    import lstchain.visualization.plot_calib as calib
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/lstchain/__init__.py", line 5, in <module>
    from . import mc
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/lstchain/mc/__init__.py", line 1, in <module>
    from .sensitivity import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/lstchain/mc/sensitivity.py", line 5, in <module>
    from .mc import rate, weight
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/lstchain/mc/mc.py", line 4, in <module>
    from gammapy.modeling.models import LogParabolaSpectralModel
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/gammapy/modeling/models/__init__.py", line 5, in <module>
    from .cube import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/gammapy/modeling/models/cube.py", line 6, in <module>
    from gammapy.maps import Map, MapAxis, RegionGeom, WcsGeom
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/gammapy/maps/__init__.py", line 3, in <module>
    from .core import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/gammapy/maps/core.py", line 9, in <module>
    from gammapy.maps.hpx import HpxGeom
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/gammapy/maps/hpx.py", line 11, in <module>
    from .wcs import WcsGeom
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/gammapy/maps/wcs.py", line 15, in <module>
    from regions import SkyRegion
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/regions/__init__.py", line 23, in <module>
    from .shapes import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/regions/shapes/__init__.py", line 4, in <module>
    from .circle import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/regions/shapes/circle.py", line 11, in <module>
    from .._geometry import circular_overlap_grid
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/regions/_geometry/__init__.py", line 5, in <module>
    from .circular_overlap import *
  File "__init__.pxd", line 242, in init regions._geometry.circular_overlap
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 278, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 337, in _init_builder
    self.events.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/lstosa/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 118, in emit
    (listener.handler, name), exc) from exc
sphinx.errors.ExtensionError: Handler <function process_automodsumm_generation at 0x7ff44420a0e0> for event 'builder-inited' threw an exception (exception: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject)

Extension error:
Handler <function process_automodsumm_generation at 0x7ff44420a0e0> for event 'builder-inited' threw an exception (exception: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject)

```

**Comment by stsewd** [comment]
Looks like an incompatibility with numpy and some C dep, looks like you are already using conda, probabbly better use conda to install numpy https://docs.readthedocs.io/en/stable/config-file/v2.html#conda, also you can try mocking https://docs.readthedocs.io/en/stable/faq.html?highlight=mocking#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by morcuended** [comment]
Thanks for the advice @stsewd. I finally got it to work by installing NumPy with conda using https://gitlab.cta-observatory.org/cta-array-elements/lst/analysis/lstosa/-/blob/master/.readthedocs.yml and https://gitlab.cta-observatory.org/cta-array-elements/lst/analysis/lstosa/-/blob/master/docs/environment.yml
