### ISSUE TITLE
Docker install of ext-theme fails if repository is not checked out first

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#7805]
I'm not sure exactly what the fix is, but it seems docker compose does something funny with the volumes if the host path for the repository does not exist at the time of `docker.build`.

### To reproduce

* Remove ext-theme checkout if it exists
* `inv docker.build` with `GITHUB_TOKEN` env var set
* ext and ext-theme will be installed
* `inv docker.shell -c web` -- this might fail
* `python`
* `import readthedocsext.theme` will fail, complaining about import paths:

```
celery_1     | Error processing line 1 of /usr/local/lib/python3.6/dist-packages/readthedocsext-theme-nspkg.pth:
celery_1     | 
celery_1     |   Traceback (most recent call last):
celery_1     |     File "/usr/lib/python3.6/site.py", line 174, in addpackage
celery_1     |       exec(line)
celery_1     |     File "<string>", line 1, in <module>
celery_1     |     File "<frozen importlib._bootstrap>", line 568, in module_from_spec
celery_1     |   AttributeError: 'NoneType' object has no attribute 'loader'
```

### What happened

As far as I can gather:

* Docker build process starts, tries to create volumes
* Host path for `ext-theme` doesn't exist, docker creates a mystery volume (:shrug:)
* Build process completes, ext-theme was installed to mystery volume
* Mystery volume is discarded
* You'll notice there is no `ext-theme` path in your host path, or if there is, it is completely empty
* Starting the container again, the ext-theme volume mounts the now empty path
* Python is unhappy and expects a python package installed at the location of the ext-theme volume mount

**Comment by agjohnson** [comment]
Just to note the temporary fix if you hit this:

```
% echo GITHUB_TOKEN="<TOKEN>"
% inv docker.build
% inv docker.up -we
```

And you should be able to see the templates. The actual fix for this is probably to unconditionally create the volume mount paths, but only try to checkout and install the package if the GITHUB_TOKEN is set. Maybe :shrug:

**Comment by humitos** [comment]
That `echo` command may be an `export` instead.

**Comment by agjohnson** [comment]
Oops! Updated.

**Comment by astrojuanlu** [comment]
That `.pth` file smells like packaging trouble. I see some commits going back and forth with namespace packages. Perhaps there's a way to simplify that?

**Comment by agjohnson** [comment]
Well, it's packaging trouble because of the bug with installation via docker, it wasn't directly a packaging issue. The underlying issue is that docker needs `GITHUB_TOKEN` during image build to successfully install the package on the first pass. If you don't do this, you will get the error above or the new templates are not usable even though the repository might be checked out on the host system.

**Comment by stsewd** [comment]
Our docs now mention cloning all required repos https://github.com/readthedocs/readthedocs.org/blob/4c4cf484b9ba071d78b17d509c229c68090df629/docs/dev/install.rst?plain=1#L37-L43
