### ISSUE TITLE
DoesNotExist: Version matching query does not exist

### ISSUE THREAD

**Issue by espdev** [readthedocs/readthedocs.org#805]
I have installed RTD (from github master) as local private server. I have used "Installation guide" (http://read-the-docs.readthedocs.org/en/latest/install.html). I use `sqlite` temporarily.

I'm trying to make the build doc for `pip` and `virtualenv`. I'm getting an error:

```
[28/Apr/2014 03:35:09] "GET /projects/pip/ HTTP/1.1" 200 9197
[28/Apr/2014 03:35:16] "GET /dashboard/pip/edit/ HTTP/1.1" 200 13643
2014-04-28 03:35:42,724 - haystack.simple_backend - WARNING - update is not implemented in this backend
update is not implemented in this backend
[28/Apr/2014 03:35:42] WARNING [haystack.simple_backend:32] update is not implemented in this backend
[28/Apr/2014 03:35:42] ERROR [projects.models:295] failed to symlink project
Traceback (most recent call last):
  File "/home/user/venvs/rtd/checkouts/readthedocs.org/readthedocs/projects/models.py", line 293, in save
    symlink(project=self.slug)
  File "/home/user/venvs/rtd/checkouts/readthedocs.org/readthedocs/projects/utils.py", line 31, in symlink
    v = version_from_slug(project, version)
  File "/home/user/venvs/rtd/checkouts/readthedocs.org/readthedocs/projects/utils.py", line 26, in version_from_slug
    v = Version.objects.get(project__slug=slug, slug=version)
  File "/home/user/venvs/rtd/local/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/user/venvs/rtd/local/lib/python2.7/site-packages/django/db/models/query.py", line 366, in get
    % self.model._meta.object_name)
DoesNotExist: Version matching query does not exist.
```

**Comment by GodfatherThe** [comment]
I followed the default install doc (http://docs.readthedocs.org/en/latest/install.html) on my VM with Windows and I'm getting the same error when trying to do "manage.py update_repos pip"

C:\readthedocs>manage.py update_repos pip
[22/May/2015 17:32:30] INFO [core.management.commands.update_repos:63] Building
Pip
Traceback (most recent call last):
  File "C:\readthedocs\manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
399, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 242,
 in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 285,
 in execute
    output = self.handle(*args, **options)
  File "C:\readthedocs\core\management\commands\update_repos.py", line 64, in ha
ndle
    trigger_build(project=p, force=force)
  File "C:\readthedocs\core\utils.py", line 85, in trigger_build
    version = project.versions.get(slug='latest')
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 151, in
 get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 310, in g
et
    self.model._meta.object_name)
builds.models.DoesNotExist: Version matching query does not exist.

**Comment by cheprus** [comment]
erichulser, 
> you can replace ‘pip’ with the name of any added project.
It is from the doc
