### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by LudvigEk** [readthedocs/readthedocs.org#8066]
## Details

* Read the Docs project URL: https://aligater.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/aligater/builds/13400435/
* Read the Docs username (if applicable): LudvigEk

## Expected Result

Docs to build and include autodoc documentation

## Actual Result

Build passes but doesn't include autodoc docstrings. My package includes two cython modules, so I am building the package with setuptools in virtualenv. However, reading the raw build log says it failed to import with this error:
`
Couldn't import AGCythonUtils, error: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /home/docs/checkouts/readthedocs.org/user_builds/aligater/checkouts/latest/aligater/AGCythonUtils.cpython-37m-x86_64-linux-gnu.so)`

This seems to be from failing to link to libm, which is used in AGCythonUtils.pyx. 
In the setup.py, I refer to libm in setuptools.Extension as:

`sourcefiles1 = ['aligater/AGCythonUtils.pyx']`
`ext1 =Extension("aligater.AGCythonUtils", sourcefiles1,libraries=["m"],language='c++', include_dirs=[np.get_include(),"./aligater"])`

Package builds (and documentation builds) fine locally, ubuntu 20.04. 
I realise this error is just me failing to build the package inside the readthedocs virtualenv - but I have no idea how to fix this or where to look for solutions.

**Comment by astrojuanlu** [comment]
Hi @LudvigEk, thanks for using Read the Docs!

The reason for the error you observe is that the default build environment ([our `latest` Docker image](https://docs.readthedocs.io/en/stable/config-file/v2.html?highlight=default#build-image)) [uses Ubuntu 18.04](https://github.com/readthedocs/readthedocs-docker-images#read-the-docs---docker-images), which ships an older version of glibc:

```
$ docker run -it --rm --name rtd-test readthedocs/build:7.0 bash
docs@4e6f3903e123:/$ /lib/x86_64-linux-gnu/libc.so.6 
GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.4) stable release version 2.27.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 7.5.0.
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.
```

In fact, using this same Docker image I can reproduce the problem locally:

```
docs@4e6f3903e123:~$ curl -sLO https://github.com/LudvigEk/aligater/archive/refs/heads/master.zip                                                                                                                                             
docs@4e6f3903e123:~$ unzip -q master.zip                                                                                                                                                                                                      
docs@4e6f3903e123:~$ cd aligater-master/                                                                                                                                                                                                      
docs@4e6f3903e123:~/aligater-master$ python3.7 setup.py install --force                                                 
running install                                 
Compiling aligater/AGCython.pyx because it changed.                                                                    
Compiling aligater/AGCythonUtils.pyx because it changed.
[1/2] Cythonizing aligater/AGCython.pyx
/home/docs/aligater-master/.eggs/Cython-0.29.22-py3.7-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/docs/ali
gater-master/aligater/AGCython.pyx          
  tree = Parsing.p_module(s, pxd, full_module_name)                                                                                                                                                                                           
[2/2] Cythonizing aligater/AGCythonUtils.pyx
/home/docs/aligater-master/.eggs/Cython-0.29.22-py3.7-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/docs/aligater-master/aligater/AGCythonUtils.pyx                                                                                
  tree = Parsing.p_module(s, pxd, full_module_name)                                                                                                                                                                                           
running bdist_egg                                                                                                                                                                                                                             
running egg_info                                                                                                                                                                                                                              
creating aligater.egg-info                         
writing aligater.egg-info/PKG-INFO                                                                                                                                                                                                            writing dependency_links to aligater.egg-info/dependency_links.txt
writing requirements to aligater.egg-info/requires.txt    
writing top-level names to aligater.egg-info/top_level.txt
writing manifest file 'aligater.egg-info/SOURCES.txt'
reading manifest file 'aligater.egg-info/SOURCES.txt'
writing manifest file 'aligater.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'aligater.AGCython' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/aligater
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/docs/.pyenv/versions/3.7.9/lib/python3.7/site-packages/numpy/core/include -I./aligater -I/home/docs/.pyenv/versions/3.7.9/include/python3.7m -c ali
gater/AGCython.cpp -o build/temp.linux-x86_64-3.7/aligater/AGCython.o
...
Using /home/docs/.pyenv/versions/3.7.9/lib/python3.7/site-packages/joblib-1.0.1-py3.7.egg
Finished processing dependencies for aligater==0.1.0
docs@4e6f3903e123:~/aligater-master$ python3.7
Python 3.7.9 (default, Feb  2 2021, 10:10:46) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aligater
AliGater started in terminal mode
Couldn't import AGCythonUtils, error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/docs/aligater-master/aligater/AGCythonUtils.cpython-37m-x86_64-linux-gnu.so)
Do you have a python 3.6+ environment active?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/docs/aligater-master/aligater/__init__.py", line 17, in <module>
    raise(e)
  File "/home/docs/aligater-master/aligater/__init__.py", line 11, in <module>
    from aligater.AGCythonUtils import *
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/docs/aligater-master/aligater/AGCythonUtils.cpython-37m-x86_64-linux-gnu.so)
```

I am not an expert in Cython but I think your solutions in the short term are:

1. Try to understand how to make a Cython library work with an older version of glibc,
2. [Use conda for the build](https://docs.readthedocs.io/en/stable/guides/conda.html) so you can install a newer version of glibc

Does this help?

**Comment by LudvigEk** [comment]
Hi, and thanks for making the effort to reproduce on your end!
A bit worrying if my package doesn't build properly on Ubuntu 18.04, I'm slightly more confused after this but at least I get a starting point for debugging. 
Thanks!

**Comment by LudvigEk** [comment]
Solved by following the steps here https://snorfalorpagus.net/blog/2016/07/17/compiling-python-extensions-for-old-glibc-versions/

In my case I've used 'exp' and 'log' from libc.math which wanted GLIBC 2.29, but fine with using older GLIBC definitions of those, so I created and included a glibc_version_fix.h containing:

```
__asm__(".symver log,log@GLIBC_2.2.5");
__asm__(".symver exp,exp@GLIBC_2.2.5");
```

**Comment by astrojuanlu** [comment]
Thanks for sharing the solution @LudvigEk, glad you got it working!
