### ISSUE TITLE
Build fails when creating virtualenv

### ISSUE THREAD

**Issue by ZedThree** [readthedocs/readthedocs.org#8075]
## Details

* Read the Docs project URL: https://bout-dev.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/bout-dev/builds/13448929/
* Read the Docs username (if applicable):

## Expected Result

Project builds successfully

## Actual Result

Project build fails when creating the virtualenv, here's the relevant raw log snippet:

```
[rtd-command-info] start-time: 2021-04-07T14:53:01.290754Z, end-time: 2021-04-07T14:53:01.295018Z, duration: 0, exit-code: -1
python3.7 -mvirtualenv --system-site-packages /home/docs/checkouts/readthedocs.org/user_builds/bout-dev/envs/2272
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 162, in run
    env=environment,
  File "/home/docs/lib/python3.6/site-packages/sentry_sdk/integrations/stdlib.py", line 190, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)  # type: ignore
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3.7': 'python3.7'
```

I notice that the traceback references a python3.6 file, but is trying to run the command with python3.7.

The project built successfully a couple of days ago, and I don't believe we've touched either any Sphinx nor RTD config since then.

**Comment by pllim** [comment]
I am seeing a similar error but only for a subset of the builds (thus far). For example, for the builds associated with astropy/astropy#11490 , it passed [about 1.5 hours ago](https://readthedocs.org/projects/astropy/builds/13448599/) but then [started failing](https://readthedocs.org/projects/astropy/builds/13449044/) and been failing since, but only for that pull request, which does not even touch the RTD settings.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 162, in run
    env=environment,
  File "/home/docs/lib/python3.6/site-packages/sentry_sdk/integrations/stdlib.py", line 190, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)  # type: ignore
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3.8': 'python3.8'
```

**Comment by ericholscher** [comment]
Hrm, a random system issue, my favorite kind to debug. Thanks for reporting this -- we're also seeing it on our monitoring builds (https://readthedocs.org/projects/time-test/builds/13449439/) which haven't changed. Definitely something on our side, we'll look into it.

**Comment by leonarduschen** [comment]
Read the Docs project URL: https://readthedocs.org/projects/pysloth/
Build URL (if applicable): https://readthedocs.org/projects/pysloth/builds/13449698/
Read the Docs username (if applicable): leonarduschen

Same here

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 162, in run
    env=environment,
  File "/home/docs/lib/python3.6/site-packages/sentry_sdk/integrations/stdlib.py", line 190, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)  # type: ignore
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3.7': 'python3.7'
```

---

Interestingly, only latest build is failing, stable builds works fine, even though both branches are at the exact same state.

**Comment by ericholscher** [comment]
We believe we've tracked this issue down, please let us know if it happens again.
