### ISSUE TITLE
Sphinx 4.1.0 is completely broken on ReadTheDocs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#8337]
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-docs/envs/1393/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-docs/envs/1393/lib/python3.7/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-docs/envs/1393/lib/python3.7/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-docs/envs/1393/lib/python3.7/site-packages/sphinx/registry.py", line 433, in load_extension
    err) from err
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.epub3 (exception: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' (/home/docs/checkouts/readthedocs.org/user_builds/frc-docs/envs/1393/lib/python3.7/site-packages/sphinx/deprecation.py))

Extension error:
Could not import extension sphinx.builders.epub3 (exception: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' (/home/docs/checkouts/readthedocs.org/user_builds/frc-docs/envs/1393/lib/python3.7/site-packages/sphinx/deprecation.py))
```

https://readthedocs.org/projects/frc-docs/builds/14224436/

PR: https://github.com/wpilibsuite/frc-docs/pull/1393

**Comment by stsewd** [comment]
Hi, this looks like an upstream issue https://github.com/sphinx-doc/sphinx/issues/9434
