### ISSUE TITLE
Builds failing (SyntaxError in funcparserlib) with no changes to config.

### ISSUE THREAD

**Issue by elParaguayo** [readthedocs/readthedocs.org#8575]
## Details

* Read the Docs project URL: https://qtile.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/qtile/builds/14954819/
* Read the Docs username (if applicable):

## Expected Result

Docs build after each commit to the master branch but it stopped working about a month ago. Looking at the build logs, the original error message (in the [first failed build](https://readthedocs.org/projects/qtile/builds/14642188/)) was:
```
Running Sphinx v4.1.2
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/setuptools_scm/git.py:94: UserWarning: "/home/docs/checkouts/readthedocs.org/user_builds/qtile/checkouts/latest" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 237, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 429, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinxcontrib/seqdiag.py", line 26, in <module>
    import seqdiag.utils.rst.nodes
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/seqdiag/utils/rst/nodes.py", line 16, in <module>
    from blockdiag.utils.rst import nodes
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/blockdiag/utils/rst/nodes.py", line 21, in <module>
    import blockdiag.builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/blockdiag/builder.py", line 16, in <module>
    from blockdiag import parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/blockdiag/parser.py", line 43, in <module>
    from funcparserlib.parser import (a, finished, forward_decl, many, maybe, skip,
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/funcparserlib/parser.py", line 123
    except NoParseError, e:
                       ^
SyntaxError: invalid syntax
```

In the [latest failure](https://readthedocs.org/projects/qtile/builds/14954819/) the error is now:
```
Running Sphinx v4.2.0
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/setuptools_scm/git.py:94: UserWarning: "/home/docs/checkouts/readthedocs.org/user_builds/qtile/checkouts/latest" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 237, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 429, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinxcontrib/seqdiag.py", line 26, in <module>
    import seqdiag.utils.rst.nodes
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/seqdiag/utils/rst/nodes.py", line 16, in <module>
    from blockdiag.utils.rst import nodes
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/blockdiag/utils/rst/nodes.py", line 21, in <module>
    import blockdiag.builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/blockdiag/builder.py", line 16, in <module>
    from blockdiag import parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/blockdiag/parser.py", line 42, in <module>
    from funcparserlib.lexer import LexerError, Token, make_tokenizer
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/funcparserlib/lexer.py", line 80
    def match_specs(specs, str, i, (line, pos)):
                                   ^
SyntaxError: invalid syntax
```

Nothing had changed in the config in the commit that had the first unsuccessful build.

Apologies if I've missed something obvious but I didn't see these error messages in my searches or in the issue history here.

**Comment by elParaguayo** [comment]
Thanks. I'm not aware that we're including it anywhere. I don't see it in any of our configs!
