### ISSUE TITLE
TypeError: argument to reversed() must be a sequence

### ISSUE THREAD

**Issue by boblemaire** [readthedocs/readthedocs.org#8642]
## Details

* Read the Docs project URL: https://github.com/boblemaire/IoTaWatt.git
* Build URL (if applicable):
* Read the Docs username (if applicable): bob@overeasy.com

## Expected Result

Build a version of my Docs directory and make it available in readthedocs

## Actual Result

Build fails. 
![Screenshot 2021-10-31 at 15-41-09 IoTaWatt Read the Docs](https://user-images.githubusercontent.com/3860127/139598979-27ee1a30-203d-4ce9-a6da-bab37fedc82a.png)

Ran into same problem with latest version and thought I did something wrong, but this is a rebuild of an archived release in my repo that had built fine before.  Have been using (and donating) for several years with no problems.  Not very fluent in the Sphynx/py environment but had followed your docs and it was working fine.  I don't see anything in the docs about breaking changes.  If this is a user error, it would be retroactive.  I'd try to figure it out but don't really know where to start.

**Comment by astrojuanlu** [comment]
Please check out #8616 , #8618, #8640.

**Comment by boblemaire** [comment]
@astrojuanlu  Thanks for the fast response, but it is not helpful.  It seems my last successful builds 2.5 months ago used python 2.7.  So I cannot replicate that environment.  Going with the suggestions mentioned above, there are half-dozen different examples of .readthedocs.yaml and requirements.txt.  It seems like there are quite a few people experiencing this problem.  Python and Sphinx are not part of my skillset.  It's a simple docs file, isn't there a set of .readthedocs.yaml and requirements.docs that will get around this problem.  I'm happy to put the files into my repo, but I have no idea what the requirements are or what is compatible with what.  That's why I use the readthedocs service to cook my docs into html.  Please advise what I might change with these files to make them work.

# File: .readthedocs.yaml

version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

# File: docs/requirements.txt

sphinx==3.4.3
sphinx_rtd_theme==0.5.1
readthedocs-sphinx-search==0.1.0rc3
docutils<0.18


I still get the same error:


Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 27 source files that are out of date
updating environment: 27 added, 0 changed, 0 removed
reading sources... [  3%] CTbasics
reading sources... [  7%] CTconfig

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 245, in apply
    apply_source_workaround(n)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: argument to reversed() must be a sequence

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/iotawatt/envs/master/lib/python2.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: argument to reversed() must be a sequence
The full traceback has been saved in /tmp/sphinx-err-K1RbI9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Command time: 0s Return: 2
