### ISSUE TITLE
AttributeError: 'HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by scardena** [readthedocs/readthedocs.org#9031]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pystardog/
* Build URL (if applicable): https://readthedocs.org/projects/pystardog/builds/16415817/

## Expected Result

Build should be successful using python 3.9, and latest version of sphinx

## Actual Result
errors with
```
Running Sphinx v4.4.0
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/sphinx/application.py", line 230, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/sphinx/application.py", line 387, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/sphinx/registry.py", line 446, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/recommonmark/__init__.py", line 9, in setup
    from .parser import CommonMarkParser
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/recommonmark/parser.py", line 9, in <module>
    from commonmark import Parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/commonmark/__init__.py", line 4, in <module>
    from commonmark.main import commonmark
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/commonmark/main.py", line 14, in <module>
    from commonmark.blocks import Parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/commonmark/blocks.py", line 5, in <module>
    from commonmark import common
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/commonmark/common.py", line 14, in <module>
    HTMLunescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystardog/envs/fix-fix-broken-documentation/lib/python3.9/site-packages/commonmark/common.py", line 14, in <module>
    HTMLunescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
The full traceback has been saved in /tmp/sphinx-err-253rmklv.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
This is how my .readthedocs.yaml file looks like:
```
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
   configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
   install:
   - requirements: docs/requirements.txt
```
Downgrading to python 3.8 fixes it, but that's just a workaround

**Comment by ericholscher** [comment]
@scardena This looks like an issue with recommonmark, which is now deprecated. We recommend using MyST for this: https://github.com/readthedocs/recommonmark/issues/221
