### ISSUE TITLE
MkDocs build fails, AttributeError: module 'jinja2' has no attribute 'contextfilter'

### ISSUE THREAD

**Issue by KanchiMoe** [readthedocs/readthedocs.org#9064]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/rtd-test-310322/
* Build URL (if applicable): https://readthedocs.org/projects/rtd-test-310322/builds/16519341/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/KanchiMoe/

## Expected Result

Build should succeed, using the bare minimum configuration for an MkDocs documentation site.

Build has worked previously in the past (2 weeks ago) using the same configuration.

## Actual Result

Build using MkDocs fails.

Build logs:

```console
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-test-310322/envs/latest/lib/python3.7/site-packages/mkdocs/__main__.py", line 14, in <module>
    from mkdocs import config
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-test-310322/envs/latest/lib/python3.7/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-test-310322/envs/latest/lib/python3.7/site-packages/mkdocs/config/defaults.py", line 4, in <module>
    from mkdocs.config import config_options
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-test-310322/envs/latest/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 8, in <module>
    from mkdocs import utils, theme, plugins
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-test-310322/envs/latest/lib/python3.7/site-packages/mkdocs/theme.py", line 9, in <module>
    from mkdocs.utils import filters
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-test-310322/envs/latest/lib/python3.7/site-packages/mkdocs/utils/filters.py", line 11, in <module>
    @jinja2.contextfilter
AttributeError: module 'jinja2' has no attribute 'contextfilter'
```
This seems related to #9052 (and maybe pallets/jinja/pull/1544) when doing a search on this repo for `contextfilter`.

Some project settings:

* Repository type: git
* Programming Language: python
*  Documentation type: Mkdocs
*  Python Interpreter: CPython 3.x

This does not appear to impact Sphinx.

**Comment by stsewd** [comment]
Hi, this is a problem with your dependencies, you need to pin Jinja2 or update your mkdocs version. https://github.com/mkdocs/mkdocs/issues/2799 https://twitter.com/readthedocs/status/1507388916013314048

**Comment by BurtHarris** [comment]
I'm seeing this same message after just having installed Docker on Win11 and running the Tutorial.  I recognize this is not the Docker repository, but it is the place that a Bing search for the error message turns up first.  

For anyone else, it seems the place to look if you are running Docker is 
https://forums.docker.com/t/jinja-mkdocs-issue-breaks-docker101tutorial/122671
