### ISSUE TITLE
Build fails on missing readthedocs-dynamic-include.js

### ISSUE THREAD

**Issue by QuentinFra** [readthedocs/readthedocs.org#910]
I am having this bug when trying to build my documentation whereas everything was fine a month ago. I get this error in the build: 

Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/application.py", line 221, in build
    self.emit('build-finished', None)
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/application.py", line 400, in emit
    results.append(callback(self, *args))
  File "/home/docs/local/lib/python2.7/site-packages/readthedocs_ext/readthedocs.py", line 31, in copy_media
    copy_static_entry(source, dest_dir, app.builder, ctx)
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/util/**init**.py", line 154, in copy_static_entry
    fdst = open(target[:-2], 'w', encoding='utf-8')
  File "/home/docs/lib/python2.7/codecs.py", line 878, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/var/build/user_builds/partoo-api-docs/checkouts/latest/_build/html/_static/readthedocs-dynamic-include.js'

My project is here:
https://readthedocs.org/builds/partoo-api-docs/

**Comment by mscuthbert** [comment]
This issue seems to be recurring again on my project, music21.  Getting essentially the same error (though in 3.X it's a FileNotFoundError)

```python
build succeeded, 1 warning.
Copying readthedocs-dynamic-include.js_t... 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/music21/envs/latest/lib/python3.4/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/music21/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 282, in build
    self.emit('build-finished', None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/music21/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/music21/envs/latest/lib/python3.4/site-packages/readthedocs_ext/readthedocs.py", line 39, in copy_media
    copy_static_entry(source, dest_dir, app.builder, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/music21/envs/latest/lib/python3.4/site-packages/sphinx/util/__init__.py", line 164, in copy_static_entry
    fdst = open(target[:-2], 'w', encoding='utf-8')
  File "/home/docs/checkouts/readthedocs.org/user_builds/music21/envs/latest/lib/python3.4/codecs.py", line 891, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/music21/checkouts/latest/music21/documentation/autogenerated/_build/html/_static/readthedocs-dynamic-include.js'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/music21/envs/latest/lib/python3.4/codecs.py", line 891, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/music21/checkouts/latest/music21/documentation/autogenerated/_build/html/_static/readthedocs-dynamic-include.js'
The full traceback has been saved in /tmp/sphinx-err-csz2t_8t.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by mscuthbert** [comment]
The sphinx build previously warned that there was no index.rst file in the directory (it was getting deleted by a previous part of the script accidentally).  When it was replaced, this part succeeded, so this might be part of the solution -- without an index.rst file there won't be a .js_t file to copy.
