### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools.command.build'

### ISSUE THREAD

**Issue by Fengrui-Liu** [readthedocs/readthedocs.org#9354]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/streamad/
* Build URL (if applicable): https://readthedocs.org/projects/streamad/builds/17220508/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/liufr/

## Expected Result

*A description of what you wanted to happen*

A [build](https://readthedocs.org/projects/streamad/builds/17098259/) has passed a week ago, however, another [build](https://readthedocs.org/projects/streamad/builds/17220508/) with same repo fails today,

Logs
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/streamad/checkouts/latest
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-uroha_sg/streamad.egg-info
      writing /tmp/pip-pip-egg-info-uroha_sg/streamad.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-uroha_sg/streamad.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-uroha_sg/streamad.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-uroha_sg/streamad.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-uroha_sg/streamad.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/checkouts/latest/setup.py", line 14, in <module>
          setup(
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/command/sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/command/sdist.py", line 111, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/command/build_py.py", line 29, in finalize_options
          orig.build_py.finalize_options(self)
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/command/build_py.py", line 43, in finalize_options
          self.set_undefined_options('build',
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/cmd.py", line 286, in set_undefined_options
          src_cmd_obj = self.distribution.get_command_obj(src_cmd)
        File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/distutils/dist.py", line 857, in get_command_obj
          klass = self.get_command_class(command)
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/setuptools/dist.py", line 887, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
          return self.resolve()
        File "/home/docs/checkouts/readthedocs.org/user_builds/streamad/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Actual Result

ModuleNotFoundError: No module named 'setuptools.command.build'

Anyone has an idea? Thanks!

**Comment by Fengrui-Liu** [comment]
btw, this repo works well on my laptop 😄 I'm afraid it is a readthedocs bug

**Comment by humitos** [comment]
I'm not sure if this could be the reason, but Read the Docs is installing `setuptools<58.3.0` as part of the setup and your package depends on `setuptools>62.0.0`: https://github.com/Fengrui-Liu/StreamAD/blob/main/setup.py#L26 . I think that could be conflicting.

Can you try using `build.jobs.post_create_environment` to run `pip install -U setuptools` so we can confirm that's the issue? See https://docs.readthedocs.io/en/latest/build-customization.html
