### ISSUE TITLE
Build fails with exception "Could not import extension sphinx_toolbox.more_autodoc.autoprotocol"

### ISSUE THREAD

**Issue by LarrySnyder** [readthedocs/readthedocs.org#9481]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/stockpyl/
* Build URL (if applicable): https://readthedocs.org/projects/stockpyl/builds/17648725/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/LarrySnyder/

## Expected Result

The build passes.

## Actual Result

The build fails with log:

```
Running Sphinx v5.1.1

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 442, in load_extension
    mod = import_module(extname)
  File "/home/docs/.asdf/installs/python/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx_toolbox/more_autodoc/autoprotocol.py", line 153, in <module>
    from sphinx_toolbox.more_autodoc.generic_bases import _add_generic_bases
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx_toolbox/more_autodoc/generic_bases.py", line 86, in <module>
    from sphinx_toolbox.more_autosummary import PatchedAutoSummClassDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx_toolbox/more_autosummary/__init__.py", line 170, in <module>
    from sphinx.ext.autodoc.importer import get_module_members
ImportError: cannot import name 'get_module_members' from 'sphinx.ext.autodoc.importer' (/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 222, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 400, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 455, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx_toolbox/__init__.py", line 95, in setup
    app.setup_extension("sphinx_toolbox.more_autodoc.autoprotocol")
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 400, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 445, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_toolbox.more_autodoc.autoprotocol (exception: cannot import name 'get_module_members' from 'sphinx.ext.autodoc.importer' (/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py))

Extension error:
Could not import extension sphinx_toolbox.more_autodoc.autoprotocol (exception: cannot import name 'get_module_members' from 'sphinx.ext.autodoc.importer' (/home/docs/checkouts/readthedocs.org/user_builds/stockpyl/envs/latest/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py))
```

The [preceding build](https://readthedocs.org/projects/stockpyl/builds/17496913/) built fine, and very little changed in the project between the two commits. 

I'm newish to RTD so I'm sorry if I'm missing something obvious. And I'm happy to help debug if there's something I can do from my end. Thanks!

**Comment by stsewd** [comment]
Hi! I see that the main difference between your latest successful build is the sphinx version.

The sphinx-toolbox extension isn't compatible with the latest version of sphinx https://github.com/sphinx-toolbox/sphinx-toolbox/pull/111. You can fix this by explicitly set the sphinx version the extension is compatible with (4.5.0 from your last succesfull build) https://github.com/LarrySnyder/stockpyl/blob/master/requirements.txt

**Comment by LarrySnyder** [comment]
That worked. I added  

```    sphinx==4.5.0```

to `install_requires` to my `setup.cfg.` Thanks for the help.
