### ISSUE TITLE
Latest version of my project is not building even though the PR are working just fine

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#9517]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sepal-doc
* Build URL (if applicable): https://docs.sepal.io/en/latest/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/borntobealive/

## Expected Result

I would like my documentation to build itself.

## Actual Result

The PR build are all passing but when I merge to main, the latest version build is constantly failing. I don't understand what differnece there is between these different builds. 

The error is the following: 

```
WARNING: Could not fetch remote image: https://sentinels.copernicus.eu/documents/247904/3944045/Sentinel-1-Revisit-Coverage-Frequency-Geometry-2019.jpeg [time data 'Tue, 01 Oct 2019 19:27:47 GST' does not match format '%a, %d %b %Y %H:%M:%S %Z']
/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/checkouts/latest/docs/source/cookbook/ccdc.rst:28: WARNING: unknown node type: <btn: >

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 277, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 301, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 367, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 559, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 569, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/builders/_epub_base.py", line 367, in write_doc
    super().write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 665, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/writers/html.py", line 59, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 2 more times]
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/nodes.py", line 240, in walkabout
    visitor.dispatch_departure(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/sphinx/util/docutils.py", line 583, in dispatch_departure
    super().dispatch_departure(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/nodes.py", line 2034, in dispatch_departure
    return method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: btn

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/sepal-doc/envs/latest/lib/python3.9/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: btn
The full traceback has been saved in /tmp/sphinx-err-nc4vbfj7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Again the strange thing is that only latest version is crashing when it should have no difference with the PR build

![image](https://user-images.githubusercontent.com/12596392/185356915-80d775ff-0eda-4940-9ff8-0147d68ae101.png)

**Comment by stsewd** [comment]
Hi, your PRs are using a different configuration file 

https://github.com/openforis/sepal-doc/blob/0438c1e85b93ceb63634245eb2539dca31d63d3c/.readthedocs.yml

than your main branch

https://github.com/openforis/sepal-doc/blob/b55356f9fcabff88fa4e911fc59c1f19f1bb65bb/.readthedocs.yaml

This is probably because you are creating your PRs from an outdated branch

**Comment by 12rambau** [comment]
I think the first one were effectively old branches relying on older version of main but the latest PR (https://github.com/openforis/sepal-doc/pull/189) are using the exact same one.   
- main: https://github.com/openforis/sepal-doc/blob/b55356f9fcabff88fa4e911fc59c1f19f1bb65bb/.readthedocs.yaml
- time-series: https://github.com/openforis/sepal-doc/blob/1c09987f4125171f3ff33ada48d6a4a67b4dfc33/.readthedocs.yaml

main is still not building and 189 worked like a charm. 

Looking at the error I send I recognize the first warning. I got it my personal machine when the language of the computer is set to french; so the date format is not corresponding anymore (note that I don't know what is this function is as I'm simply using the image directive).

**Comment by stsewd** [comment]
@12rambau your build is failing while building the EPUB format https://readthedocs.org/projects/sepal-doc/builds/17832214/, we don't build PDF or EPUB on PRs, that's why you don't see that error there. But the error looks related to an extension that isn't configured to work with EPUB builds, this isn't a problem with rtd.

> NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: btn

**Comment by 12rambau** [comment]
Thanks, I didn't know that some builds were ignored during PR, let me open an issue on the btn extension.
