### ISSUE TITLE
unresolver.py - dataclass() got an unexpected keyword argument 'slots'

### ISSUE THREAD

**Issue by quasarenergy** [readthedocs/readthedocs.org#9647]
## Details

Installing readthedocs in local machine using https://haha.readthedocs.io/en/latest/install.html#get-and-run-read-the-docs.

# Tools/Env:
- Python 3.9
- Centos 8 Stream 

## Expected Result

* `python3 manage.py migrate` would build the database

## Actual Result

* `python3 manage.py migrate` is failing with:
```python
STEP 10/14: RUN python3 manage.py makemigrations
[debug    ] Using slumber v2.              [readthedocs.api.v2.client] api_host=http://127.0.0.1:8000 username=test
Traceback (most recent call last):
  File "/apps/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/apps/readthedocs/core/apps.py", line 15, in ready
    import readthedocs.core.signals  # noqa
  File "/apps/readthedocs/core/signals.py", line 14, in <module>
    from readthedocs.core.unresolver import unresolve
  File "/apps/readthedocs/core/unresolver.py", line 15, in <module>
    @dataclass(slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'
Error: error building at STEP "RUN python3 manage.py makemigrations": error while running runtime: exit status 1

```

**Comment by humitos** [comment]
Hi @quasarenergy! Those are not the official docs for Read the Docs and they pretty outdated. Please, follow https://dev.readthedocs.io/en/latest/install.html and let us know if you have any issues with them.

**Comment by stsewd** [comment]
I'm closing this issue since those aren't the steps from our official documentation (https://dev.readthedocs.io/en/latest/install.html). But if you are curious about the error, it's because our application needs python 3.10 (no `slots` in python 3.9)

**Comment by quasarenergy** [comment]
Thanks @humitos and @stsewd. Sorry, I could not respond back, but that helped.
