### ISSUE TITLE
Building error with sphinx/util/inspect.py [return isinstance(obj, typing.NewType)]

### ISSUE THREAD

**Issue by MartinPdeS** [readthedocs/readthedocs.org#9668]
Hello, 
I have a problem building documentation on RTD with Python 3.10. It appears that the issue root from the inspect submodule. However, the build process seems to work perfectly fine locally. I am wondering if RTD install custom module that would cause the errors.

The YML file I am using is pretty simple. The project is available on the following link: [SuPyMode](https://readthedocs.org/projects/supymodes)

YML file: ------------------------------------------------
version: 1

build:
  image: testing
  os: ubuntu-latest
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: true

python:
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
------------------------------------------------

Here is the full traceback outputted by RTD
Traceback: -------------------------------------------

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 310, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 326, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 433, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 454, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 510, in read_doc
    publisher.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/io.py", line 104, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/parsers.py", line 78, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 1165, in indent
    elements = self.block_quote(indented, line_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 1180, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/directive.py", line 148, in run
    documenter.generate(more_content=self.content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1798, in generate
    return super().generate(more_content=more_content,
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 954, in generate
    self.document_members(all_members)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1789, in document_members
    super().document_members(all_members)
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 813, in document_members
    classes = [cls for cls in self.documenters.values()
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 814, in <listcomp>
    if cls.can_document_member(member, mname, isattr, self)]
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 2106, in can_document_member
    return inspect.isNewType(member) and isattr
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/util/inspect.py", line 153, in isNewType
    return isinstance(obj, typing.NewType)
TypeError: isinstance() arg 2 must be a type, a tuple of types or a union

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/supymodes/envs/latest/lib/python3.10/site-packages/sphinx/util/inspect.py", line 153, in isNewType
    return isinstance(obj, typing.NewType)
TypeError: isinstance() arg 2 must be a type, a tuple of types or a union
------------------------------------------------

**Comment by stsewd** [comment]
Hi, looks like you solved the problem https://readthedocs.org/projects/supymodes/builds/20392712/? If you have other problem, please create a new issue.
