### ISSUE TITLE
How can I fix "inv docker build"  authorization error in readthedoc installation.

### ISSUE THREAD

**Issue by pilgrimage80** [readthedocs/readthedocs.org#9895]
Hi I created a virtual environment with python3.8 pip.

mkdir pipvm
cd pipvm
cd bin

(pyt38) [redhat@localhost bin]$ source activate
(pyt38) [redhat@localhost bin]$

I am entering the pip virtual environment.

In this environment, I need to install with the steps in the following document.

https://dev.readthedocs.io/en/latest/install.html

(pyt38) [redhat@localhost bin]$  inv docker.build

but I get this error.

Traceback (most recent call last):
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
return self.version(api_version=False)["ApiVersion"]
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/docker/api/daemon.py", line 181, in version
return self._result(self._get(url), json=True)
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
return f(self, *args, **kwargs)
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/docker/api/client.py", line 237, in _get
return self.get(url, **self._set_request_timeout(kwargs))
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/requests/sessions.py", line 600, in get
return self.request("GET", url, **kwargs)
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/home/redhat/rtddocker/pipvm/pyt38/lib64/python3.8/site-packages/requests/adapters.py", line 547, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

How can I fix this authorization error? When rooted, " inv docker.build" installs without any problem. But I keep getting a warning message about Pip not to run as root, so how can I run inv docker.build without root without getting an authorization error.

**Comment by benjaoming** [comment]
> When rooted, " inv docker.build" installs without any problem.

This indicates that you have a docker issue that should be addressed by asking in a forum about Docker. With that said, your local user probably doesn't have access to connect to the docker daemon.

Before you run anything related to Read the Docs, make sure that your docker environment is actually working for the user you are running it with :+1:
