### ISSUE TITLE
Validate if branch exists before creating project

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9942]
When importing a project using "Import Manually", the branch field can be specified or left empty (to choose the repo's default branch).

Let's say that we specify it like this:

![image](https://user-images.githubusercontent.com/374612/214585955-0c2c8b8d-c854-4bca-b31e-4513485686ad.png)

Validation is needed
--------------------

If the field is specified with a branch that does NOT exist, the project is again "locked" in the same state as https://github.com/readthedocs/readthedocs.org/issues/9367 - because the initial checkout fails (the branch does not exist), we will not be able to select a new branch using the Settings UI:

![image](https://user-images.githubusercontent.com/374612/214586900-8044a7bd-ced9-4a78-9d7e-1cd2e255fcd6.png)

New failures
------------

We are also in a situation where #9424 may have caused a new Version.DoesNotExist error (this happened after I pulled the changes in that PR)

@humitos can you quickly triage if you also get this `DoesNotExist` if importing a project with an invalid branch and add the Accepted label in that case?

```
Environment:


Request Method: POST
Request URL: http://devthedocs.org/dashboard/import/manual/

Django Version: 3.2.16
Python Version: 3.10.6
Installed Applications:
['django.contrib.auth',
 'django.contrib.admin',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.humanize',
 'readthedocs.core',
 'django.contrib.staticfiles',
 'dj_pagination',
 'taggit',
 'django_gravatar',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'annoying',
 'django_extensions',
 'crispy_forms',
 'messages_extends',
 'django_elasticsearch_dsl',
 'django_filters',
 'polymorphic',
 'simple_history',
 'djstripe',
 'readthedocs.projects',
 'readthedocs.organizations',
 'readthedocs.builds',
 'readthedocs.doc_builder',
 'readthedocs.oauth',
 'readthedocs.redirects',
 'readthedocs.sso',
 'readthedocs.audit',
 'readthedocs.rtd_tests',
 'readthedocs.api.v2',
 'readthedocs.api.v3',
 'readthedocs.gold',
 'readthedocs.payments',
 'readthedocs.subscriptions',
 'readthedocs.notifications',
 'readthedocs.integrations',
 'readthedocs.analytics',
 'readthedocs.sphinx_domains',
 'readthedocs.search',
 'readthedocs.embed',
 'readthedocs.telemetry',
 'readthedocs.domains',
 'readthedocs.invitations',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'allauth.socialaccount.providers.gitlab',
 'allauth.socialaccount.providers.bitbucket',
 'allauth.socialaccount.providers.bitbucket_oauth2',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'readthedocs.core.middleware.NullCharactersMiddleware',
 'readthedocs.core.middleware.ReadTheDocsSessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'dj_pagination.middleware.PaginationMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'csp.middleware.CSPMiddleware',
 'readthedocs.core.middleware.ReferrerPolicyMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'readthedocs.core.logs.ReadTheDocsRequestMiddleware',
 'django_structlog.middlewares.CeleryMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/formtools/wizard/views.py", line 244, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/src/app/checkouts/readthedocs.org/readthedocs/projects/views/private.py", line 301, in post
    return super().post(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/formtools/wizard/views.py", line 302, in post
    return self.render_done(form, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/formtools/wizard/views.py", line 358, in render_done
    done_response = self.done(list(final_forms.values()), form_dict=final_forms, **kwargs)
  File "/usr/src/app/checkouts/readthedocs.org/readthedocs/projects/views/private.py", line 340, in done
    self.finish_import_project(self.request, project, tags)
  File "/usr/src/app/checkouts/readthedocs.org/readthedocs/projects/views/mixins.py", line 135, in finish_import_project
    self.trigger_initial_build(project, request.user)
  File "/usr/src/app/checkouts/readthedocs.org/readthedocs/projects/views/mixins.py", line 145, in trigger_initial_build
    update_docs, build = prepare_build(project)
  File "/usr/src/app/checkouts/readthedocs.org/readthedocs/core/utils/__init__.py", line 62, in prepare_build
    version = project.versions.get(slug=default_version)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /dashboard/import/manual/
Exception Value: Version matching query does not exist.
```

**Comment by stsewd** [comment]
I think re-saving the project should fix this problem, that way the project goes back to choose the default branch.
